// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module Filter(	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
  input         clock,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
                reset,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
  input  [31:0] io_data_in_0,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:145:14
                io_data_in_1,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:145:14
                io_data_in_2,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:145:14
  output        io_valid_out,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:145:14
  output [31:0] io_data_to_Fifo,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:145:14
                io_data_to_rebuffer_0,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:145:14
                io_data_to_rebuffer_1,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:145:14
                io_data_to_rebuffer_2	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:145:14
);

  reg  [31:0] cnt;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:156:20
  wire        io_valid_out_0 = cnt < 32'h5;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:156:20, :177:{15,27}
  always @(posedge clock) begin	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
    if (reset)	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
      cnt <= 32'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:156:20
    else if (cnt == 32'h6)	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:156:20, :160:{13,23}
      cnt <= 32'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:156:20
    else	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:160:13
      cnt <= cnt + 32'h1;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:156:20, :163:16
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
    `ifdef FIRRTL_BEFORE_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
      `FIRRTL_BEFORE_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
      automatic logic [31:0] _RANDOM[0:0];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
      `ifdef INIT_RANDOM_PROLOG_	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
        `INIT_RANDOM_PROLOG_	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
        cnt = _RANDOM[/*Zero width*/ 1'b0];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7, :156:20
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
      `FIRRTL_AFTER_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_valid_out = io_valid_out_0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7, :177:15
  assign io_data_to_Fifo = io_valid_out_0 ? io_data_in_1 : 32'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7, :156:20, :173:19, :177:{15,35}, :179:23
  assign io_data_to_rebuffer_0 = io_data_in_0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
  assign io_data_to_rebuffer_1 = io_data_in_1;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
  assign io_data_to_rebuffer_2 = io_data_in_2;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
endmodule

module Filter_1(	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
  input         clock,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
                reset,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
  input  [31:0] io_data_in_0,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:145:14
                io_data_in_1,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:145:14
                io_data_in_2,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:145:14
  output        io_valid_out,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:145:14
  output [31:0] io_data_to_Fifo,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:145:14
                io_data_to_rebuffer_0,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:145:14
                io_data_to_rebuffer_1,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:145:14
                io_data_to_rebuffer_2	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:145:14
);

  reg  [31:0] cnt;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:156:20
  wire        io_valid_out_0 = (|(cnt[31:2])) & cnt < 32'h9;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:156:20, :160:23, :184:{15,28,35}
  always @(posedge clock) begin	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
    if (reset)	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
      cnt <= 32'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:156:20
    else if (cnt == 32'h9)	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:156:20, :160:{13,23}
      cnt <= 32'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:156:20
    else	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:160:13
      cnt <= cnt + 32'h1;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:156:20, :163:16
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
    `ifdef FIRRTL_BEFORE_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
      `FIRRTL_BEFORE_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
      automatic logic [31:0] _RANDOM[0:0];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
      `ifdef INIT_RANDOM_PROLOG_	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
        `INIT_RANDOM_PROLOG_	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
        cnt = _RANDOM[/*Zero width*/ 1'b0];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7, :156:20
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
      `FIRRTL_AFTER_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_valid_out = io_valid_out_0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7, :184:28
  assign io_data_to_Fifo = io_valid_out_0 ? io_data_in_2 : 32'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7, :156:20, :173:19, :184:{28,51}, :185:23
  assign io_data_to_rebuffer_0 = io_data_in_0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
  assign io_data_to_rebuffer_1 = io_data_in_1;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
  assign io_data_to_rebuffer_2 = io_data_in_2;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
endmodule

module Filter_2(	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
  input         clock,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
                reset,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
  input  [31:0] io_data_in_0,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:145:14
                io_data_in_1,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:145:14
                io_data_in_2,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:145:14
  output        io_valid_out,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:145:14
  output [31:0] io_data_to_Fifo,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:145:14
                io_data_to_rebuffer_0,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:145:14
                io_data_to_rebuffer_1,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:145:14
                io_data_to_rebuffer_2	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:145:14
);

  reg  [31:0] cnt;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:156:20
  wire        io_valid_out_0 = cnt > 32'h6 & cnt < 32'hC;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:156:20, :160:23, :190:{14,19,27,34}
  always @(posedge clock) begin	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
    if (reset)	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
      cnt <= 32'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:156:20
    else if (cnt == 32'hC)	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:156:20, :160:{13,23}
      cnt <= 32'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:156:20
    else	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:160:13
      cnt <= cnt + 32'h1;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:156:20, :163:16
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
    `ifdef FIRRTL_BEFORE_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
      `FIRRTL_BEFORE_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
      automatic logic [31:0] _RANDOM[0:0];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
      `ifdef INIT_RANDOM_PROLOG_	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
        `INIT_RANDOM_PROLOG_	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
        cnt = _RANDOM[/*Zero width*/ 1'b0];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7, :156:20
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
      `FIRRTL_AFTER_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_valid_out = io_valid_out_0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7, :190:27
  assign io_data_to_Fifo = io_valid_out_0 ? io_data_in_1 : 32'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7, :156:20, :173:19, :190:{27,50}, :191:23
  assign io_data_to_rebuffer_0 = io_data_in_0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
  assign io_data_to_rebuffer_1 = io_data_in_1;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
  assign io_data_to_rebuffer_2 = io_data_in_2;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
endmodule

module Filter_3(	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
  input         clock,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
                reset,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
  input  [31:0] io_data_in_0,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:145:14
                io_data_in_1,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:145:14
                io_data_in_2,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:145:14
  output        io_valid_out,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:145:14
  output [31:0] io_data_to_Fifo,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:145:14
                io_data_to_rebuffer_0,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:145:14
                io_data_to_rebuffer_1,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:145:14
                io_data_to_rebuffer_2	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:145:14
);

  reg  [31:0] cnt;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:156:20
  wire        io_valid_out_0 = cnt > 32'h9 & cnt < 32'hF;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:156:20, :160:23, :197:{16,21,29,36}
  always @(posedge clock) begin	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
    if (reset)	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
      cnt <= 32'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:156:20
    else if (cnt == 32'hF)	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:156:20, :160:{13,23}
      cnt <= 32'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:156:20
    else	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:160:13
      cnt <= cnt + 32'h1;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:156:20, :163:16
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
    `ifdef FIRRTL_BEFORE_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
      `FIRRTL_BEFORE_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
      automatic logic [31:0] _RANDOM[0:0];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
      `ifdef INIT_RANDOM_PROLOG_	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
        `INIT_RANDOM_PROLOG_	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
        cnt = _RANDOM[/*Zero width*/ 1'b0];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7, :156:20
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
      `FIRRTL_AFTER_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_valid_out = io_valid_out_0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7, :197:29
  assign io_data_to_Fifo = io_valid_out_0 ? io_data_in_0 : 32'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7, :156:20, :173:19, :197:{29,52}, :198:25
  assign io_data_to_rebuffer_0 = io_data_in_0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
  assign io_data_to_rebuffer_1 = io_data_in_1;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
  assign io_data_to_rebuffer_2 = io_data_in_2;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
endmodule

module Filter_4(	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
  input         clock,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
                reset,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
  input  [31:0] io_data_in_1,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:145:14
  output        io_valid_out,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:145:14
  output [31:0] io_data_to_Fifo	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:145:14
);

  reg  [31:0] cnt;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:156:20
  wire        io_valid_out_0 = cnt > 32'hD;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:156:20, :203:{17,22}
  always @(posedge clock) begin	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
    if (reset)	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
      cnt <= 32'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:156:20
    else if (cnt == 32'h12)	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:156:20, :160:{13,23}
      cnt <= 32'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:156:20
    else	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:160:13
      cnt <= cnt + 32'h1;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:156:20, :163:16
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
    `ifdef FIRRTL_BEFORE_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
      `FIRRTL_BEFORE_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
      automatic logic [31:0] _RANDOM[0:0];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
      `ifdef INIT_RANDOM_PROLOG_	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
        `INIT_RANDOM_PROLOG_	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
        cnt = _RANDOM[/*Zero width*/ 1'b0];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7, :156:20
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
      `FIRRTL_AFTER_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_valid_out = io_valid_out_0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7, :203:17
  assign io_data_to_Fifo = io_valid_out_0 ? io_data_in_1 : 32'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:142:7, :156:20, :173:19, :203:{17,30}, :204:25
endmodule

module Reuse_buffer(	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:7
  input         clock,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:7
  input  [31:0] io_data_in_0,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:231:14
                io_data_in_1,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:231:14
                io_data_in_2,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:231:14
  output [31:0] io_data_out_0,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:231:14
                io_data_out_1,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:231:14
                io_data_out_2	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:231:14
);

  reg [31:0] buffer_0_0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:238:19
  reg [31:0] buffer_0_1;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:238:19
  reg [31:0] buffer_0_2;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:238:19
  reg [31:0] buffer_1_0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:238:19
  reg [31:0] buffer_1_1;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:238:19
  reg [31:0] buffer_1_2;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:238:19
  reg [31:0] buffer_2_0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:238:19
  reg [31:0] buffer_2_1;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:238:19
  reg [31:0] buffer_2_2;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:238:19
  always @(posedge clock) begin	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:7
    buffer_0_0 <= io_data_in_0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:238:19
    buffer_0_1 <= buffer_0_0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:238:19
    buffer_0_2 <= buffer_0_1;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:238:19
    buffer_1_0 <= io_data_in_1;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:238:19
    buffer_1_1 <= buffer_1_0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:238:19
    buffer_1_2 <= buffer_1_1;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:238:19
    buffer_2_0 <= io_data_in_2;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:238:19
    buffer_2_1 <= buffer_2_0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:238:19
    buffer_2_2 <= buffer_2_1;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:238:19
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:7
    `ifdef FIRRTL_BEFORE_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:7
      `FIRRTL_BEFORE_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:7
      automatic logic [31:0] _RANDOM[0:8];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:7
      `ifdef INIT_RANDOM_PROLOG_	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:7
        `INIT_RANDOM_PROLOG_	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:7
        for (logic [3:0] i = 4'h0; i < 4'h9; i += 4'h1) begin
          _RANDOM[i] = `RANDOM;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:7
        end	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:7
        buffer_0_0 = _RANDOM[4'h0];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:7, :238:19
        buffer_0_1 = _RANDOM[4'h1];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:7, :238:19
        buffer_0_2 = _RANDOM[4'h2];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:7, :238:19
        buffer_1_0 = _RANDOM[4'h3];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:7, :238:19
        buffer_1_1 = _RANDOM[4'h4];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:7, :238:19
        buffer_1_2 = _RANDOM[4'h5];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:7, :238:19
        buffer_2_0 = _RANDOM[4'h6];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:7, :238:19
        buffer_2_1 = _RANDOM[4'h7];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:7, :238:19
        buffer_2_2 = _RANDOM[4'h8];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:7, :238:19
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:7
      `FIRRTL_AFTER_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_data_out_0 = buffer_0_2;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:7, :238:19
  assign io_data_out_1 = buffer_1_2;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:7, :238:19
  assign io_data_out_2 = buffer_2_2;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:7, :238:19
endmodule

// VCS coverage exclude_file
module ram_20x32(	// src/main/scala/chisel3/util/Decoupled.scala:256:91
  input  [4:0]  R0_addr,
  input         R0_en,
                R0_clk,
  output [31:0] R0_data,
  input  [4:0]  W0_addr,
  input         W0_en,
                W0_clk,
  input  [31:0] W0_data
);

  reg [31:0] Memory[0:19];	// src/main/scala/chisel3/util/Decoupled.scala:256:91
  always @(posedge W0_clk) begin	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    if (W0_en & 1'h1)	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      Memory[W0_addr] <= W0_data;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    reg [31:0] _RANDOM_MEM;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    initial begin	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      `INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      `ifdef RANDOMIZE_MEM_INIT	// src/main/scala/chisel3/util/Decoupled.scala:256:91
        for (logic [4:0] i = 5'h0; i < 5'h14; i += 5'h1) begin
          _RANDOM_MEM = `RANDOM;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
          Memory[i] = _RANDOM_MEM;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
        end	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 32'bx;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
endmodule

module Queue20_UInt32(	// src/main/scala/chisel3/util/Decoupled.scala:243:7
  input         clock,	// src/main/scala/chisel3/util/Decoupled.scala:243:7
                reset,	// src/main/scala/chisel3/util/Decoupled.scala:243:7
                io_enq_valid,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input  [31:0] io_enq_bits,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input         io_deq_ready,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  output [31:0] io_deq_bits	// src/main/scala/chisel3/util/Decoupled.scala:255:14
);

  wire       io_enq_ready;	// src/main/scala/chisel3/util/Decoupled.scala:286:19
  reg  [4:0] enq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg  [4:0] deq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg        maybe_full;	// src/main/scala/chisel3/util/Decoupled.scala:259:27
  wire       ptr_match = enq_ptr_value == deq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:260:33
  wire       do_enq = io_enq_ready & io_enq_valid;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :286:19
  assign io_enq_ready = ~(ptr_match & maybe_full);	// src/main/scala/chisel3/util/Decoupled.scala:259:27, :260:33, :262:24, :286:19
  always @(posedge clock) begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    if (reset) begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      enq_ptr_value <= 5'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
      deq_ptr_value <= 5'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
      maybe_full <= 1'h0;	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :259:27
    end
    else begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      automatic logic do_deq;	// src/main/scala/chisel3/util/Decoupled.scala:51:35
      do_deq = io_deq_ready & ~(ptr_match & ~maybe_full);	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27, :260:33, :261:{25,28}, :285:19
      if (do_enq) begin	// src/main/scala/chisel3/util/Decoupled.scala:51:35
        if (enq_ptr_value == 5'h13)	// src/main/scala/chisel3/util/Counter.scala:61:40, :73:24
          enq_ptr_value <= 5'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
        else	// src/main/scala/chisel3/util/Counter.scala:73:24
          enq_ptr_value <= enq_ptr_value + 5'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      end
      if (do_deq) begin	// src/main/scala/chisel3/util/Decoupled.scala:51:35
        if (deq_ptr_value == 5'h13)	// src/main/scala/chisel3/util/Counter.scala:61:40, :73:24
          deq_ptr_value <= 5'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
        else	// src/main/scala/chisel3/util/Counter.scala:73:24
          deq_ptr_value <= deq_ptr_value + 5'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      end
      if (~(do_enq == do_deq))	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27, :276:{15,27}, :277:16
        maybe_full <= do_enq;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      automatic logic [31:0] _RANDOM[0:0];	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Decoupled.scala:243:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/chisel3/util/Decoupled.scala:243:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/chisel3/util/Decoupled.scala:243:7
        enq_ptr_value = _RANDOM[/*Zero width*/ 1'b0][4:0];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:243:7
        deq_ptr_value = _RANDOM[/*Zero width*/ 1'b0][9:5];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:243:7
        maybe_full = _RANDOM[/*Zero width*/ 1'b0][10];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:243:7, :259:27
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ram_20x32 ram_ext (	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    .R0_addr (deq_ptr_value),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .R0_en   (1'h1),	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    .R0_clk  (clock),
    .R0_data (io_deq_bits),
    .W0_addr (enq_ptr_value),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .W0_en   (do_enq),	// src/main/scala/chisel3/util/Decoupled.scala:51:35
    .W0_clk  (clock),
    .W0_data (io_enq_bits)
  );
endmodule

module FIFO(	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:215:7
  input         clock,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:215:7
                reset,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:215:7
                io_enq_valid,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:216:14
  input  [31:0] io_enq_bits,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:216:14
  input         io_deq_ready,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:216:14
  output [31:0] io_deq_bits	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:216:14
);

  Queue20_UInt32 q (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:221:17
    .clock        (clock),
    .reset        (reset),
    .io_enq_valid (io_enq_valid),
    .io_enq_bits  (io_enq_bits),
    .io_deq_ready (io_deq_ready),
    .io_deq_bits  (io_deq_bits)
  );
endmodule

// VCS coverage exclude_file
module ram_15x32(	// src/main/scala/chisel3/util/Decoupled.scala:256:91
  input  [3:0]  R0_addr,
  input         R0_en,
                R0_clk,
  output [31:0] R0_data,
  input  [3:0]  W0_addr,
  input         W0_en,
                W0_clk,
  input  [31:0] W0_data
);

  reg [31:0] Memory[0:14];	// src/main/scala/chisel3/util/Decoupled.scala:256:91
  always @(posedge W0_clk) begin	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    if (W0_en & 1'h1)	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      Memory[W0_addr] <= W0_data;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    reg [31:0] _RANDOM_MEM;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    initial begin	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      `INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      `ifdef RANDOMIZE_MEM_INIT	// src/main/scala/chisel3/util/Decoupled.scala:256:91
        for (logic [3:0] i = 4'h0; i < 4'hF; i += 4'h1) begin
          _RANDOM_MEM = `RANDOM;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
          Memory[i] = _RANDOM_MEM;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
        end	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 32'bx;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
endmodule

module Queue15_UInt32(	// src/main/scala/chisel3/util/Decoupled.scala:243:7
  input         clock,	// src/main/scala/chisel3/util/Decoupled.scala:243:7
                reset,	// src/main/scala/chisel3/util/Decoupled.scala:243:7
                io_enq_valid,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input  [31:0] io_enq_bits,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input         io_deq_ready,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  output [31:0] io_deq_bits	// src/main/scala/chisel3/util/Decoupled.scala:255:14
);

  wire       io_enq_ready;	// src/main/scala/chisel3/util/Decoupled.scala:286:19
  reg  [3:0] enq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg  [3:0] deq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg        maybe_full;	// src/main/scala/chisel3/util/Decoupled.scala:259:27
  wire       ptr_match = enq_ptr_value == deq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:260:33
  wire       do_enq = io_enq_ready & io_enq_valid;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :286:19
  assign io_enq_ready = ~(ptr_match & maybe_full);	// src/main/scala/chisel3/util/Decoupled.scala:259:27, :260:33, :262:24, :286:19
  always @(posedge clock) begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    if (reset) begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      enq_ptr_value <= 4'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
      deq_ptr_value <= 4'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
      maybe_full <= 1'h0;	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :259:27
    end
    else begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      automatic logic do_deq;	// src/main/scala/chisel3/util/Decoupled.scala:51:35
      do_deq = io_deq_ready & ~(ptr_match & ~maybe_full);	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27, :260:33, :261:{25,28}, :285:19
      if (do_enq) begin	// src/main/scala/chisel3/util/Decoupled.scala:51:35
        if (enq_ptr_value == 4'hE)	// src/main/scala/chisel3/util/Counter.scala:61:40, :73:24
          enq_ptr_value <= 4'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
        else	// src/main/scala/chisel3/util/Counter.scala:73:24
          enq_ptr_value <= enq_ptr_value + 4'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      end
      if (do_deq) begin	// src/main/scala/chisel3/util/Decoupled.scala:51:35
        if (deq_ptr_value == 4'hE)	// src/main/scala/chisel3/util/Counter.scala:61:40, :73:24
          deq_ptr_value <= 4'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
        else	// src/main/scala/chisel3/util/Counter.scala:73:24
          deq_ptr_value <= deq_ptr_value + 4'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      end
      if (~(do_enq == do_deq))	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27, :276:{15,27}, :277:16
        maybe_full <= do_enq;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      automatic logic [31:0] _RANDOM[0:0];	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Decoupled.scala:243:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/chisel3/util/Decoupled.scala:243:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/chisel3/util/Decoupled.scala:243:7
        enq_ptr_value = _RANDOM[/*Zero width*/ 1'b0][3:0];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:243:7
        deq_ptr_value = _RANDOM[/*Zero width*/ 1'b0][7:4];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:243:7
        maybe_full = _RANDOM[/*Zero width*/ 1'b0][8];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:243:7, :259:27
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ram_15x32 ram_ext (	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    .R0_addr (deq_ptr_value),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .R0_en   (1'h1),	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    .R0_clk  (clock),
    .R0_data (io_deq_bits),
    .W0_addr (enq_ptr_value),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .W0_en   (do_enq),	// src/main/scala/chisel3/util/Decoupled.scala:51:35
    .W0_clk  (clock),
    .W0_data (io_enq_bits)
  );
endmodule

module FIFO_1(	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:215:7
  input         clock,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:215:7
                reset,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:215:7
                io_enq_valid,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:216:14
  input  [31:0] io_enq_bits,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:216:14
  input         io_deq_ready,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:216:14
  output [31:0] io_deq_bits	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:216:14
);

  Queue15_UInt32 q (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:221:17
    .clock        (clock),
    .reset        (reset),
    .io_enq_valid (io_enq_valid),
    .io_enq_bits  (io_enq_bits),
    .io_deq_ready (io_deq_ready),
    .io_deq_bits  (io_deq_bits)
  );
endmodule

// VCS coverage exclude_file
module ram_11x32(	// src/main/scala/chisel3/util/Decoupled.scala:256:91
  input  [3:0]  R0_addr,
  input         R0_en,
                R0_clk,
  output [31:0] R0_data,
  input  [3:0]  W0_addr,
  input         W0_en,
                W0_clk,
  input  [31:0] W0_data
);

  reg [31:0] Memory[0:10];	// src/main/scala/chisel3/util/Decoupled.scala:256:91
  always @(posedge W0_clk) begin	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    if (W0_en & 1'h1)	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      Memory[W0_addr] <= W0_data;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    reg [31:0] _RANDOM_MEM;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    initial begin	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      `INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      `ifdef RANDOMIZE_MEM_INIT	// src/main/scala/chisel3/util/Decoupled.scala:256:91
        for (logic [3:0] i = 4'h0; i < 4'hB; i += 4'h1) begin
          _RANDOM_MEM = `RANDOM;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
          Memory[i] = _RANDOM_MEM;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
        end	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 32'bx;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
endmodule

module Queue11_UInt32(	// src/main/scala/chisel3/util/Decoupled.scala:243:7
  input         clock,	// src/main/scala/chisel3/util/Decoupled.scala:243:7
                reset,	// src/main/scala/chisel3/util/Decoupled.scala:243:7
                io_enq_valid,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input  [31:0] io_enq_bits,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input         io_deq_ready,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  output [31:0] io_deq_bits	// src/main/scala/chisel3/util/Decoupled.scala:255:14
);

  wire       io_enq_ready;	// src/main/scala/chisel3/util/Decoupled.scala:286:19
  reg  [3:0] enq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg  [3:0] deq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg        maybe_full;	// src/main/scala/chisel3/util/Decoupled.scala:259:27
  wire       ptr_match = enq_ptr_value == deq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:260:33
  wire       do_enq = io_enq_ready & io_enq_valid;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :286:19
  assign io_enq_ready = ~(ptr_match & maybe_full);	// src/main/scala/chisel3/util/Decoupled.scala:259:27, :260:33, :262:24, :286:19
  always @(posedge clock) begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    if (reset) begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      enq_ptr_value <= 4'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
      deq_ptr_value <= 4'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
      maybe_full <= 1'h0;	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :259:27
    end
    else begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      automatic logic do_deq;	// src/main/scala/chisel3/util/Decoupled.scala:51:35
      do_deq = io_deq_ready & ~(ptr_match & ~maybe_full);	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27, :260:33, :261:{25,28}, :285:19
      if (do_enq) begin	// src/main/scala/chisel3/util/Decoupled.scala:51:35
        if (enq_ptr_value == 4'hA)	// src/main/scala/chisel3/util/Counter.scala:61:40, :73:24
          enq_ptr_value <= 4'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
        else	// src/main/scala/chisel3/util/Counter.scala:73:24
          enq_ptr_value <= enq_ptr_value + 4'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      end
      if (do_deq) begin	// src/main/scala/chisel3/util/Decoupled.scala:51:35
        if (deq_ptr_value == 4'hA)	// src/main/scala/chisel3/util/Counter.scala:61:40, :73:24
          deq_ptr_value <= 4'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
        else	// src/main/scala/chisel3/util/Counter.scala:73:24
          deq_ptr_value <= deq_ptr_value + 4'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      end
      if (~(do_enq == do_deq))	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27, :276:{15,27}, :277:16
        maybe_full <= do_enq;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      automatic logic [31:0] _RANDOM[0:0];	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Decoupled.scala:243:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/chisel3/util/Decoupled.scala:243:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/chisel3/util/Decoupled.scala:243:7
        enq_ptr_value = _RANDOM[/*Zero width*/ 1'b0][3:0];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:243:7
        deq_ptr_value = _RANDOM[/*Zero width*/ 1'b0][7:4];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:243:7
        maybe_full = _RANDOM[/*Zero width*/ 1'b0][8];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:243:7, :259:27
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ram_11x32 ram_ext (	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    .R0_addr (deq_ptr_value),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .R0_en   (1'h1),	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    .R0_clk  (clock),
    .R0_data (io_deq_bits),
    .W0_addr (enq_ptr_value),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .W0_en   (do_enq),	// src/main/scala/chisel3/util/Decoupled.scala:51:35
    .W0_clk  (clock),
    .W0_data (io_enq_bits)
  );
endmodule

module FIFO_2(	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:215:7
  input         clock,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:215:7
                reset,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:215:7
                io_enq_valid,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:216:14
  input  [31:0] io_enq_bits,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:216:14
  input         io_deq_ready,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:216:14
  output [31:0] io_deq_bits	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:216:14
);

  Queue11_UInt32 q (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:221:17
    .clock        (clock),
    .reset        (reset),
    .io_enq_valid (io_enq_valid),
    .io_enq_bits  (io_enq_bits),
    .io_deq_ready (io_deq_ready),
    .io_deq_bits  (io_deq_bits)
  );
endmodule

// VCS coverage exclude_file
module ram_7x32(	// src/main/scala/chisel3/util/Decoupled.scala:256:91
  input  [2:0]  R0_addr,
  input         R0_en,
                R0_clk,
  output [31:0] R0_data,
  input  [2:0]  W0_addr,
  input         W0_en,
                W0_clk,
  input  [31:0] W0_data
);

  reg [31:0] Memory[0:6];	// src/main/scala/chisel3/util/Decoupled.scala:256:91
  always @(posedge W0_clk) begin	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    if (W0_en & 1'h1)	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      Memory[W0_addr] <= W0_data;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    reg [31:0] _RANDOM_MEM;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    initial begin	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      `INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      `ifdef RANDOMIZE_MEM_INIT	// src/main/scala/chisel3/util/Decoupled.scala:256:91
        for (logic [2:0] i = 3'h0; i < 3'h7; i += 3'h1) begin
          _RANDOM_MEM = `RANDOM;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
          Memory[i] = _RANDOM_MEM;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
        end	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 32'bx;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
endmodule

module Queue7_UInt32(	// src/main/scala/chisel3/util/Decoupled.scala:243:7
  input         clock,	// src/main/scala/chisel3/util/Decoupled.scala:243:7
                reset,	// src/main/scala/chisel3/util/Decoupled.scala:243:7
                io_enq_valid,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input  [31:0] io_enq_bits,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input         io_deq_ready,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  output [31:0] io_deq_bits	// src/main/scala/chisel3/util/Decoupled.scala:255:14
);

  wire       io_enq_ready;	// src/main/scala/chisel3/util/Decoupled.scala:286:19
  reg  [2:0] enq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg  [2:0] deq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg        maybe_full;	// src/main/scala/chisel3/util/Decoupled.scala:259:27
  wire       ptr_match = enq_ptr_value == deq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:260:33
  wire       do_enq = io_enq_ready & io_enq_valid;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :286:19
  assign io_enq_ready = ~(ptr_match & maybe_full);	// src/main/scala/chisel3/util/Decoupled.scala:259:27, :260:33, :262:24, :286:19
  always @(posedge clock) begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    if (reset) begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      enq_ptr_value <= 3'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
      deq_ptr_value <= 3'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
      maybe_full <= 1'h0;	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :259:27
    end
    else begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      automatic logic do_deq;	// src/main/scala/chisel3/util/Decoupled.scala:51:35
      do_deq = io_deq_ready & ~(ptr_match & ~maybe_full);	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27, :260:33, :261:{25,28}, :285:19
      if (do_enq) begin	// src/main/scala/chisel3/util/Decoupled.scala:51:35
        if (enq_ptr_value == 3'h6)	// src/main/scala/chisel3/util/Counter.scala:61:40, :73:24
          enq_ptr_value <= 3'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
        else	// src/main/scala/chisel3/util/Counter.scala:73:24
          enq_ptr_value <= enq_ptr_value + 3'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      end
      if (do_deq) begin	// src/main/scala/chisel3/util/Decoupled.scala:51:35
        if (deq_ptr_value == 3'h6)	// src/main/scala/chisel3/util/Counter.scala:61:40, :73:24
          deq_ptr_value <= 3'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
        else	// src/main/scala/chisel3/util/Counter.scala:73:24
          deq_ptr_value <= deq_ptr_value + 3'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      end
      if (~(do_enq == do_deq))	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27, :276:{15,27}, :277:16
        maybe_full <= do_enq;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      automatic logic [31:0] _RANDOM[0:0];	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Decoupled.scala:243:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/chisel3/util/Decoupled.scala:243:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/chisel3/util/Decoupled.scala:243:7
        enq_ptr_value = _RANDOM[/*Zero width*/ 1'b0][2:0];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:243:7
        deq_ptr_value = _RANDOM[/*Zero width*/ 1'b0][5:3];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:243:7
        maybe_full = _RANDOM[/*Zero width*/ 1'b0][6];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:243:7, :259:27
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ram_7x32 ram_ext (	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    .R0_addr (deq_ptr_value),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .R0_en   (1'h1),	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    .R0_clk  (clock),
    .R0_data (io_deq_bits),
    .W0_addr (enq_ptr_value),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .W0_en   (do_enq),	// src/main/scala/chisel3/util/Decoupled.scala:51:35
    .W0_clk  (clock),
    .W0_data (io_enq_bits)
  );
endmodule

module FIFO_3(	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:215:7
  input         clock,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:215:7
                reset,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:215:7
                io_enq_valid,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:216:14
  input  [31:0] io_enq_bits,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:216:14
  input         io_deq_ready,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:216:14
  output [31:0] io_deq_bits	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:216:14
);

  Queue7_UInt32 q (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:221:17
    .clock        (clock),
    .reset        (reset),
    .io_enq_valid (io_enq_valid),
    .io_enq_bits  (io_enq_bits),
    .io_deq_ready (io_deq_ready),
    .io_deq_bits  (io_deq_bits)
  );
endmodule

// VCS coverage exclude_file
module ram_5x32(	// src/main/scala/chisel3/util/Decoupled.scala:256:91
  input  [2:0]  R0_addr,
  input         R0_en,
                R0_clk,
  output [31:0] R0_data,
  input  [2:0]  W0_addr,
  input         W0_en,
                W0_clk,
  input  [31:0] W0_data
);

  reg [31:0] Memory[0:4];	// src/main/scala/chisel3/util/Decoupled.scala:256:91
  always @(posedge W0_clk) begin	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    if (W0_en & 1'h1)	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      Memory[W0_addr] <= W0_data;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    reg [31:0] _RANDOM_MEM;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    initial begin	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      `INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      `ifdef RANDOMIZE_MEM_INIT	// src/main/scala/chisel3/util/Decoupled.scala:256:91
        for (logic [2:0] i = 3'h0; i < 3'h5; i += 3'h1) begin
          _RANDOM_MEM = `RANDOM;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
          Memory[i] = _RANDOM_MEM;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
        end	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 32'bx;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
endmodule

module Queue5_UInt32(	// src/main/scala/chisel3/util/Decoupled.scala:243:7
  input         clock,	// src/main/scala/chisel3/util/Decoupled.scala:243:7
                reset,	// src/main/scala/chisel3/util/Decoupled.scala:243:7
                io_enq_valid,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input  [31:0] io_enq_bits,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input         io_deq_ready,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  output [31:0] io_deq_bits	// src/main/scala/chisel3/util/Decoupled.scala:255:14
);

  wire       io_enq_ready;	// src/main/scala/chisel3/util/Decoupled.scala:286:19
  reg  [2:0] enq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg  [2:0] deq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg        maybe_full;	// src/main/scala/chisel3/util/Decoupled.scala:259:27
  wire       ptr_match = enq_ptr_value == deq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:260:33
  wire       do_enq = io_enq_ready & io_enq_valid;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :286:19
  assign io_enq_ready = ~(ptr_match & maybe_full);	// src/main/scala/chisel3/util/Decoupled.scala:259:27, :260:33, :262:24, :286:19
  always @(posedge clock) begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    if (reset) begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      enq_ptr_value <= 3'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
      deq_ptr_value <= 3'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
      maybe_full <= 1'h0;	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :259:27
    end
    else begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      automatic logic do_deq;	// src/main/scala/chisel3/util/Decoupled.scala:51:35
      do_deq = io_deq_ready & ~(ptr_match & ~maybe_full);	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27, :260:33, :261:{25,28}, :285:19
      if (do_enq) begin	// src/main/scala/chisel3/util/Decoupled.scala:51:35
        if (enq_ptr_value == 3'h4)	// src/main/scala/chisel3/util/Counter.scala:61:40, :73:24
          enq_ptr_value <= 3'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
        else	// src/main/scala/chisel3/util/Counter.scala:73:24
          enq_ptr_value <= enq_ptr_value + 3'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      end
      if (do_deq) begin	// src/main/scala/chisel3/util/Decoupled.scala:51:35
        if (deq_ptr_value == 3'h4)	// src/main/scala/chisel3/util/Counter.scala:61:40, :73:24
          deq_ptr_value <= 3'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
        else	// src/main/scala/chisel3/util/Counter.scala:73:24
          deq_ptr_value <= deq_ptr_value + 3'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      end
      if (~(do_enq == do_deq))	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27, :276:{15,27}, :277:16
        maybe_full <= do_enq;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      automatic logic [31:0] _RANDOM[0:0];	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Decoupled.scala:243:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/chisel3/util/Decoupled.scala:243:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/chisel3/util/Decoupled.scala:243:7
        enq_ptr_value = _RANDOM[/*Zero width*/ 1'b0][2:0];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:243:7
        deq_ptr_value = _RANDOM[/*Zero width*/ 1'b0][5:3];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:243:7
        maybe_full = _RANDOM[/*Zero width*/ 1'b0][6];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:243:7, :259:27
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ram_5x32 ram_ext (	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    .R0_addr (deq_ptr_value),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .R0_en   (1'h1),	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    .R0_clk  (clock),
    .R0_data (io_deq_bits),
    .W0_addr (enq_ptr_value),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .W0_en   (do_enq),	// src/main/scala/chisel3/util/Decoupled.scala:51:35
    .W0_clk  (clock),
    .W0_data (io_enq_bits)
  );
endmodule

module FIFO_4(	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:215:7
  input         clock,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:215:7
                reset,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:215:7
                io_enq_valid,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:216:14
  input  [31:0] io_enq_bits,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:216:14
  input         io_deq_ready,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:216:14
  output [31:0] io_deq_bits	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:216:14
);

  Queue5_UInt32 q (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:221:17
    .clock        (clock),
    .reset        (reset),
    .io_enq_valid (io_enq_valid),
    .io_enq_bits  (io_enq_bits),
    .io_deq_ready (io_deq_ready),
    .io_deq_bits  (io_deq_bits)
  );
endmodule

module datapath_2d(	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:30:7
  input         clock,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:30:7
                reset,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:30:7
  input  [95:0] io_datapath_data_in,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:31:14
  input         io_datapath_ready_in,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:31:14
  output [31:0] io_datapath_data_out1,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:31:14
                io_datapath_data_out2,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:31:14
                io_datapath_data_out3,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:31:14
                io_datapath_data_out4,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:31:14
                io_datapath_data_out5	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:31:14
);

  wire [31:0] _Reuse_buffer_3_io_data_out_1;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:68:19
  wire [31:0] _Reuse_buffer_2_io_data_out_0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:67:19
  wire [31:0] _Reuse_buffer_2_io_data_out_1;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:67:19
  wire [31:0] _Reuse_buffer_2_io_data_out_2;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:67:19
  wire [31:0] _Reuse_buffer_1_io_data_out_0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:66:19
  wire [31:0] _Reuse_buffer_1_io_data_out_1;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:66:19
  wire [31:0] _Reuse_buffer_1_io_data_out_2;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:66:19
  wire [31:0] _Reuse_buffer_io_data_out_0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:65:19
  wire [31:0] _Reuse_buffer_io_data_out_1;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:65:19
  wire [31:0] _Reuse_buffer_io_data_out_2;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:65:19
  wire        _Filter_4_io_valid_out;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:60:18
  wire [31:0] _Filter_4_io_data_to_Fifo;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:60:18
  wire        _Filter_3_io_valid_out;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:59:18
  wire [31:0] _Filter_3_io_data_to_Fifo;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:59:18
  wire [31:0] _Filter_3_io_data_to_rebuffer_0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:59:18
  wire [31:0] _Filter_3_io_data_to_rebuffer_1;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:59:18
  wire [31:0] _Filter_3_io_data_to_rebuffer_2;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:59:18
  wire        _Filter_2_io_valid_out;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:58:18
  wire [31:0] _Filter_2_io_data_to_Fifo;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:58:18
  wire [31:0] _Filter_2_io_data_to_rebuffer_0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:58:18
  wire [31:0] _Filter_2_io_data_to_rebuffer_1;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:58:18
  wire [31:0] _Filter_2_io_data_to_rebuffer_2;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:58:18
  wire        _Filter_1_io_valid_out;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:57:18
  wire [31:0] _Filter_1_io_data_to_Fifo;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:57:18
  wire [31:0] _Filter_1_io_data_to_rebuffer_0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:57:18
  wire [31:0] _Filter_1_io_data_to_rebuffer_1;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:57:18
  wire [31:0] _Filter_1_io_data_to_rebuffer_2;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:57:18
  wire        _Filter_io_valid_out;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:56:18
  wire [31:0] _Filter_io_data_to_Fifo;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:56:18
  wire [31:0] _Filter_io_data_to_rebuffer_0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:56:18
  wire [31:0] _Filter_io_data_to_rebuffer_1;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:56:18
  wire [31:0] _Filter_io_data_to_rebuffer_2;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:56:18
  reg  [31:0] cnt;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:47:20
  reg         f1_deq;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:114:23
  reg         f2_deq;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:115:23
  reg         f3_deq;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:116:23
  reg         f4_deq;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:117:23
  reg         f5_deq;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:118:23
  always @(posedge clock) begin	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:30:7
    if (reset) begin	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:30:7
      cnt <= 32'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:46:24, :47:20
      f1_deq <= 1'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:51:13, :114:23
      f2_deq <= 1'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:51:13, :115:23
      f3_deq <= 1'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:51:13, :116:23
      f4_deq <= 1'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:51:13, :117:23
      f5_deq <= 1'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:51:13, :118:23
    end
    else begin	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:30:7
      automatic logic _GEN;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:121:12
      _GEN = cnt == 32'h15;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:47:20, :121:12
      cnt <= cnt + 32'h1;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:47:20, :48:12
      f1_deq <= _GEN | f1_deq;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:114:23, :121:{12,21}, :122:12
      f2_deq <= _GEN | f2_deq;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:115:23, :121:{12,21}, :124:12
      f3_deq <= _GEN | f3_deq;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:116:23, :121:{12,21}, :126:12
      f4_deq <= _GEN | f4_deq;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:117:23, :121:{12,21}, :128:12
      f5_deq <= _GEN | f5_deq;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:118:23, :121:{12,21}, :130:12
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:30:7
    `ifdef FIRRTL_BEFORE_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:30:7
      `FIRRTL_BEFORE_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:30:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:30:7
      automatic logic [31:0] _RANDOM[0:2];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:30:7
      `ifdef INIT_RANDOM_PROLOG_	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:30:7
        `INIT_RANDOM_PROLOG_	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:30:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:30:7
        for (logic [1:0] i = 2'h0; i < 2'h3; i += 2'h1) begin
          _RANDOM[i] = `RANDOM;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:30:7
        end	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:30:7
        cnt = _RANDOM[2'h1];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:30:7, :47:20
        f1_deq = _RANDOM[2'h2][0];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:30:7, :114:23
        f2_deq = _RANDOM[2'h2][1];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:30:7, :114:23, :115:23
        f3_deq = _RANDOM[2'h2][2];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:30:7, :114:23, :116:23
        f4_deq = _RANDOM[2'h2][3];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:30:7, :114:23, :117:23
        f5_deq = _RANDOM[2'h2][4];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:30:7, :114:23, :118:23
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:30:7
      `FIRRTL_AFTER_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:30:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  Filter Filter (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:56:18
    .clock                 (clock),
    .reset                 (reset),
    .io_data_in_0          (io_datapath_data_in[31:0]),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:73:41
    .io_data_in_1          (io_datapath_data_in[63:32]),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:73:41
    .io_data_in_2          (io_datapath_data_in[95:64]),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:73:41
    .io_valid_out          (_Filter_io_valid_out),
    .io_data_to_Fifo       (_Filter_io_data_to_Fifo),
    .io_data_to_rebuffer_0 (_Filter_io_data_to_rebuffer_0),
    .io_data_to_rebuffer_1 (_Filter_io_data_to_rebuffer_1),
    .io_data_to_rebuffer_2 (_Filter_io_data_to_rebuffer_2)
  );
  Filter_1 Filter_1 (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:57:18
    .clock                 (clock),
    .reset                 (reset),
    .io_data_in_0          (_Reuse_buffer_io_data_out_0),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:65:19
    .io_data_in_1          (_Reuse_buffer_io_data_out_1),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:65:19
    .io_data_in_2          (_Reuse_buffer_io_data_out_2),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:65:19
    .io_valid_out          (_Filter_1_io_valid_out),
    .io_data_to_Fifo       (_Filter_1_io_data_to_Fifo),
    .io_data_to_rebuffer_0 (_Filter_1_io_data_to_rebuffer_0),
    .io_data_to_rebuffer_1 (_Filter_1_io_data_to_rebuffer_1),
    .io_data_to_rebuffer_2 (_Filter_1_io_data_to_rebuffer_2)
  );
  Filter_2 Filter_2 (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:58:18
    .clock                 (clock),
    .reset                 (reset),
    .io_data_in_0          (_Reuse_buffer_1_io_data_out_0),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:66:19
    .io_data_in_1          (_Reuse_buffer_1_io_data_out_1),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:66:19
    .io_data_in_2          (_Reuse_buffer_1_io_data_out_2),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:66:19
    .io_valid_out          (_Filter_2_io_valid_out),
    .io_data_to_Fifo       (_Filter_2_io_data_to_Fifo),
    .io_data_to_rebuffer_0 (_Filter_2_io_data_to_rebuffer_0),
    .io_data_to_rebuffer_1 (_Filter_2_io_data_to_rebuffer_1),
    .io_data_to_rebuffer_2 (_Filter_2_io_data_to_rebuffer_2)
  );
  Filter_3 Filter_3 (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:59:18
    .clock                 (clock),
    .reset                 (reset),
    .io_data_in_0          (_Reuse_buffer_2_io_data_out_0),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:67:19
    .io_data_in_1          (_Reuse_buffer_2_io_data_out_1),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:67:19
    .io_data_in_2          (_Reuse_buffer_2_io_data_out_2),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:67:19
    .io_valid_out          (_Filter_3_io_valid_out),
    .io_data_to_Fifo       (_Filter_3_io_data_to_Fifo),
    .io_data_to_rebuffer_0 (_Filter_3_io_data_to_rebuffer_0),
    .io_data_to_rebuffer_1 (_Filter_3_io_data_to_rebuffer_1),
    .io_data_to_rebuffer_2 (_Filter_3_io_data_to_rebuffer_2)
  );
  Filter_4 Filter_4 (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:60:18
    .clock           (clock),
    .reset           (reset),
    .io_data_in_1    (_Reuse_buffer_3_io_data_out_1),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:68:19
    .io_valid_out    (_Filter_4_io_valid_out),
    .io_data_to_Fifo (_Filter_4_io_data_to_Fifo)
  );
  Reuse_buffer Reuse_buffer (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:65:19
    .clock         (clock),
    .io_data_in_0  (_Filter_io_data_to_rebuffer_0),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:56:18
    .io_data_in_1  (_Filter_io_data_to_rebuffer_1),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:56:18
    .io_data_in_2  (_Filter_io_data_to_rebuffer_2),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:56:18
    .io_data_out_0 (_Reuse_buffer_io_data_out_0),
    .io_data_out_1 (_Reuse_buffer_io_data_out_1),
    .io_data_out_2 (_Reuse_buffer_io_data_out_2)
  );
  Reuse_buffer Reuse_buffer_1 (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:66:19
    .clock         (clock),
    .io_data_in_0  (_Filter_1_io_data_to_rebuffer_0),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:57:18
    .io_data_in_1  (_Filter_1_io_data_to_rebuffer_1),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:57:18
    .io_data_in_2  (_Filter_1_io_data_to_rebuffer_2),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:57:18
    .io_data_out_0 (_Reuse_buffer_1_io_data_out_0),
    .io_data_out_1 (_Reuse_buffer_1_io_data_out_1),
    .io_data_out_2 (_Reuse_buffer_1_io_data_out_2)
  );
  Reuse_buffer Reuse_buffer_2 (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:67:19
    .clock         (clock),
    .io_data_in_0  (_Filter_2_io_data_to_rebuffer_0),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:58:18
    .io_data_in_1  (_Filter_2_io_data_to_rebuffer_1),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:58:18
    .io_data_in_2  (_Filter_2_io_data_to_rebuffer_2),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:58:18
    .io_data_out_0 (_Reuse_buffer_2_io_data_out_0),
    .io_data_out_1 (_Reuse_buffer_2_io_data_out_1),
    .io_data_out_2 (_Reuse_buffer_2_io_data_out_2)
  );
  Reuse_buffer Reuse_buffer_3 (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:68:19
    .clock         (clock),
    .io_data_in_0  (_Filter_3_io_data_to_rebuffer_0),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:59:18
    .io_data_in_1  (_Filter_3_io_data_to_rebuffer_1),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:59:18
    .io_data_in_2  (_Filter_3_io_data_to_rebuffer_2),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:59:18
    .io_data_out_0 (/* unused */),
    .io_data_out_1 (_Reuse_buffer_3_io_data_out_1),
    .io_data_out_2 (/* unused */)
  );
  FIFO fifo1 (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:88:22
    .clock        (clock),
    .reset        (reset),
    .io_enq_valid (_Filter_io_valid_out),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:56:18
    .io_enq_bits  (_Filter_io_data_to_Fifo),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:56:18
    .io_deq_ready (f1_deq),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:114:23
    .io_deq_bits  (io_datapath_data_out1)
  );
  FIFO_1 fifo2 (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:89:22
    .clock        (clock),
    .reset        (reset),
    .io_enq_valid (_Filter_1_io_valid_out),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:57:18
    .io_enq_bits  (_Filter_1_io_data_to_Fifo),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:57:18
    .io_deq_ready (f2_deq),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:115:23
    .io_deq_bits  (io_datapath_data_out2)
  );
  FIFO_2 fifo3 (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:90:22
    .clock        (clock),
    .reset        (reset),
    .io_enq_valid (_Filter_2_io_valid_out),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:58:18
    .io_enq_bits  (_Filter_2_io_data_to_Fifo),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:58:18
    .io_deq_ready (f3_deq),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:116:23
    .io_deq_bits  (io_datapath_data_out3)
  );
  FIFO_3 fifo4 (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:91:22
    .clock        (clock),
    .reset        (reset),
    .io_enq_valid (_Filter_3_io_valid_out),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:59:18
    .io_enq_bits  (_Filter_3_io_data_to_Fifo),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:59:18
    .io_deq_ready (f4_deq),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:117:23
    .io_deq_bits  (io_datapath_data_out4)
  );
  FIFO_4 fifo5 (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:92:22
    .clock        (clock),
    .reset        (reset),
    .io_enq_valid (_Filter_4_io_valid_out),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:60:18
    .io_enq_bits  (_Filter_4_io_data_to_Fifo),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:60:18
    .io_deq_ready (f5_deq),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:118:23
    .io_deq_bits  (io_datapath_data_out5)
  );
endmodule


