// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module Filter_3d(	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
  input         clock,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
                reset,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
  input  [31:0] io_data_in_1,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
                io_data_in_3,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
                io_data_in_4,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
                io_data_in_5,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
                io_data_in_7,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
  output        io_valid_out,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
  output [31:0] io_data_to_Fifo,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
                io_data_to_rebuffer_1,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
                io_data_to_rebuffer_3,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
                io_data_to_rebuffer_4,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
                io_data_to_rebuffer_5,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
                io_data_to_rebuffer_7	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
);

  reg  [31:0] cnt;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:241:20
  reg  [31:0] offset;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:245:19
  wire        io_valid_out_0 = cnt < offset + 32'h5;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:241:20, :245:19, :264:{14,23}
  always @(posedge clock) begin	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
    if (reset)	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
      cnt <= 32'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:241:20
    else if (cnt == offset + 32'h6)	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:241:20, :245:19, :247:{13,20}
      cnt <= 32'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:241:20
    else	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:247:13
      cnt <= cnt + 32'h1;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:241:20, :250:16
    offset <= 32'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:241:20, :245:19
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
    `ifdef FIRRTL_BEFORE_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
      `FIRRTL_BEFORE_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
      automatic logic [31:0] _RANDOM[0:1];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
      `ifdef INIT_RANDOM_PROLOG_	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
        `INIT_RANDOM_PROLOG_	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
        end	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
        cnt = _RANDOM[1'h0];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7, :241:20
        offset = _RANDOM[1'h1];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7, :245:19
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
      `FIRRTL_AFTER_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_valid_out = io_valid_out_0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7, :264:14
  assign io_data_to_Fifo = io_valid_out_0 ? io_data_in_4 : 32'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7, :241:20, :260:19, :264:{14,31}, :266:23
  assign io_data_to_rebuffer_1 = io_data_in_1;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
  assign io_data_to_rebuffer_3 = io_data_in_3;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
  assign io_data_to_rebuffer_4 = io_data_in_4;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
  assign io_data_to_rebuffer_5 = io_data_in_5;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
  assign io_data_to_rebuffer_7 = io_data_in_7;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
endmodule

module Filter_3d_1(	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
  input         clock,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
                reset,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
  input  [31:0] io_data_in_1,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
                io_data_in_3,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
                io_data_in_4,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
                io_data_in_5,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
                io_data_in_7,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
  output        io_valid_out,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
  output [31:0] io_data_to_Fifo,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
                io_data_to_rebuffer_3,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
                io_data_to_rebuffer_4,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
                io_data_to_rebuffer_5,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
                io_data_to_rebuffer_7	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
);

  reg  [31:0] cnt;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:241:20
  reg  [31:0] offset;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:245:19
  wire [31:0] _GEN = offset + 32'h6;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:245:19, :247:20
  wire        io_valid_out_0 = cnt > offset & cnt < _GEN;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:241:20, :245:19, :247:20, :271:{14,27,34}
  always @(posedge clock) begin	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
    if (reset)	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
      cnt <= 32'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:241:20
    else if (cnt == _GEN)	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:241:20, :247:{13,20}
      cnt <= 32'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:241:20
    else	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:247:13
      cnt <= cnt + 32'h1;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:241:20, :250:16
    offset <= 32'h3;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:245:19, :270:12
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
    `ifdef FIRRTL_BEFORE_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
      `FIRRTL_BEFORE_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
      automatic logic [31:0] _RANDOM[0:1];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
      `ifdef INIT_RANDOM_PROLOG_	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
        `INIT_RANDOM_PROLOG_	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
        end	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
        cnt = _RANDOM[1'h0];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7, :241:20
        offset = _RANDOM[1'h1];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7, :245:19
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
      `FIRRTL_AFTER_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_valid_out = io_valid_out_0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7, :271:27
  assign io_data_to_Fifo = io_valid_out_0 ? io_data_in_1 : 32'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7, :241:20, :260:19, :271:{27,47}, :272:23
  assign io_data_to_rebuffer_3 = io_data_in_3;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
  assign io_data_to_rebuffer_4 = io_data_in_4;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
  assign io_data_to_rebuffer_5 = io_data_in_5;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
  assign io_data_to_rebuffer_7 = io_data_in_7;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
endmodule

module Filter_3d_2(	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
  input         clock,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
                reset,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
  input  [31:0] io_data_in_3,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
                io_data_in_4,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
                io_data_in_5,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
                io_data_in_7,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
  output        io_valid_out,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
  output [31:0] io_data_to_Fifo,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
                io_data_to_rebuffer_4,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
                io_data_to_rebuffer_5,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
                io_data_to_rebuffer_7	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
);

  reg  [31:0] cnt;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:241:20
  reg  [31:0] offset;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:245:19
  wire [31:0] _GEN = offset + 32'h6;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:245:19, :247:20, :276:12
  wire        io_valid_out_0 = cnt > offset & cnt < _GEN;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:241:20, :245:19, :247:20, :277:{14,27,34}
  always @(posedge clock) begin	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
    if (reset)	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
      cnt <= 32'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:241:20
    else if (cnt == _GEN)	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:241:20, :247:{13,20}
      cnt <= 32'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:241:20
    else	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:247:13
      cnt <= cnt + 32'h1;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:241:20, :250:16
    offset <= 32'h6;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:245:19, :276:12
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
    `ifdef FIRRTL_BEFORE_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
      `FIRRTL_BEFORE_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
      automatic logic [31:0] _RANDOM[0:1];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
      `ifdef INIT_RANDOM_PROLOG_	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
        `INIT_RANDOM_PROLOG_	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
        end	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
        cnt = _RANDOM[1'h0];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7, :241:20
        offset = _RANDOM[1'h1];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7, :245:19
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
      `FIRRTL_AFTER_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_valid_out = io_valid_out_0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7, :277:27
  assign io_data_to_Fifo = io_valid_out_0 ? io_data_in_3 : 32'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7, :241:20, :260:19, :277:{27,47}, :278:23
  assign io_data_to_rebuffer_4 = io_data_in_4;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
  assign io_data_to_rebuffer_5 = io_data_in_5;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
  assign io_data_to_rebuffer_7 = io_data_in_7;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
endmodule

module Filter_3d_3(	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
  input         clock,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
                reset,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
  input  [31:0] io_data_in_4,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
                io_data_in_5,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
                io_data_in_7,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
  output        io_valid_out,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
  output [31:0] io_data_to_Fifo,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
                io_data_to_rebuffer_4,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
                io_data_to_rebuffer_7	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
);

  reg  [31:0] cnt;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:241:20
  reg  [31:0] offset;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:245:19
  wire [31:0] _GEN = offset + 32'h6;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:245:19, :247:20
  wire        io_valid_out_0 = cnt > offset & cnt < _GEN;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:241:20, :245:19, :247:20, :284:{14,27,34}
  always @(posedge clock) begin	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
    if (reset)	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
      cnt <= 32'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:241:20
    else if (cnt == _GEN)	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:241:20, :247:{13,20}
      cnt <= 32'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:241:20
    else	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:247:13
      cnt <= cnt + 32'h1;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:241:20, :250:16
    offset <= 32'h9;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:245:19, :283:12
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
    `ifdef FIRRTL_BEFORE_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
      `FIRRTL_BEFORE_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
      automatic logic [31:0] _RANDOM[0:1];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
      `ifdef INIT_RANDOM_PROLOG_	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
        `INIT_RANDOM_PROLOG_	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
        end	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
        cnt = _RANDOM[1'h0];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7, :241:20
        offset = _RANDOM[1'h1];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7, :245:19
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
      `FIRRTL_AFTER_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_valid_out = io_valid_out_0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7, :284:27
  assign io_data_to_Fifo = io_valid_out_0 ? io_data_in_5 : 32'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7, :241:20, :260:19, :284:{27,47}, :285:23
  assign io_data_to_rebuffer_4 = io_data_in_4;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
  assign io_data_to_rebuffer_7 = io_data_in_7;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
endmodule

module Filter_3d_4(	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
  input         clock,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
                reset,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
  input  [31:0] io_data_in_4,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
                io_data_in_7,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
  output        io_valid_out,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
  output [31:0] io_data_to_Fifo,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
                io_data_to_rebuffer_4	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
);

  reg  [31:0] cnt;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:241:20
  reg  [31:0] offset;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:245:19
  wire        io_valid_out_0 = cnt > offset + 32'h1;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:241:20, :245:19, :250:16, :290:{14,19}
  always @(posedge clock) begin	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
    if (reset)	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
      cnt <= 32'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:241:20
    else if (cnt == offset + 32'h6)	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:241:20, :245:19, :247:{13,20}
      cnt <= 32'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:241:20
    else	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:247:13
      cnt <= cnt + 32'h1;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:241:20, :250:16
    offset <= 32'hC;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:245:19, :289:12
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
    `ifdef FIRRTL_BEFORE_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
      `FIRRTL_BEFORE_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
      automatic logic [31:0] _RANDOM[0:1];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
      `ifdef INIT_RANDOM_PROLOG_	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
        `INIT_RANDOM_PROLOG_	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
        end	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
        cnt = _RANDOM[1'h0];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7, :241:20
        offset = _RANDOM[1'h1];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7, :245:19
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
      `FIRRTL_AFTER_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_valid_out = io_valid_out_0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7, :290:14
  assign io_data_to_Fifo = io_valid_out_0 ? io_data_in_7 : 32'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7, :241:20, :260:19, :290:{14,27}, :291:23
  assign io_data_to_rebuffer_4 = io_data_in_4;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
endmodule

module Filter_3d_5(	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
  input         clock,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
                reset,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
  input  [31:0] io_data_in_4,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
  output        io_valid_out,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
  output [31:0] io_data_to_Fifo	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:230:14
);

  reg  [31:0] cnt;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:241:20
  reg  [31:0] offset;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:245:19
  wire        io_valid_out_0 = cnt > offset + 32'h1;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:241:20, :245:19, :250:16, :297:{14,19}
  always @(posedge clock) begin	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
    if (reset)	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
      cnt <= 32'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:241:20
    else if (cnt == offset + 32'h6)	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:241:20, :245:19, :247:{13,20}
      cnt <= 32'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:241:20
    else	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:247:13
      cnt <= cnt + 32'h1;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:241:20, :250:16
    offset <= 32'hF;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:245:19, :296:12
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
    `ifdef FIRRTL_BEFORE_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
      `FIRRTL_BEFORE_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
      automatic logic [31:0] _RANDOM[0:1];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
      `ifdef INIT_RANDOM_PROLOG_	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
        `INIT_RANDOM_PROLOG_	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
        end	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
        cnt = _RANDOM[1'h0];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7, :241:20
        offset = _RANDOM[1'h1];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7, :245:19
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
      `FIRRTL_AFTER_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_valid_out = io_valid_out_0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7, :297:14
  assign io_data_to_Fifo = io_valid_out_0 ? io_data_in_4 : 32'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:219:7, :241:20, :260:19, :297:{14,27}, :298:23
endmodule

// VCS coverage exclude_file
module ram_26x32(	// src/main/scala/chisel3/util/Decoupled.scala:256:91
  input  [4:0]  R0_addr,
  input         R0_en,
                R0_clk,
  output [31:0] R0_data,
  input  [4:0]  W0_addr,
  input         W0_en,
                W0_clk,
  input  [31:0] W0_data
);

  reg [31:0] Memory[0:25];	// src/main/scala/chisel3/util/Decoupled.scala:256:91
  always @(posedge W0_clk) begin	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    if (W0_en & 1'h1)	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      Memory[W0_addr] <= W0_data;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    reg [31:0] _RANDOM_MEM;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    initial begin	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      `INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      `ifdef RANDOMIZE_MEM_INIT	// src/main/scala/chisel3/util/Decoupled.scala:256:91
        for (logic [4:0] i = 5'h0; i < 5'h1A; i += 5'h1) begin
          _RANDOM_MEM = `RANDOM;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
          Memory[i] = _RANDOM_MEM;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
        end	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 32'bx;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
endmodule

module Queue26_UInt32(	// src/main/scala/chisel3/util/Decoupled.scala:243:7
  input         clock,	// src/main/scala/chisel3/util/Decoupled.scala:243:7
                reset,	// src/main/scala/chisel3/util/Decoupled.scala:243:7
                io_enq_valid,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input  [31:0] io_enq_bits,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input         io_deq_ready,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  output [31:0] io_deq_bits	// src/main/scala/chisel3/util/Decoupled.scala:255:14
);

  wire       io_enq_ready;	// src/main/scala/chisel3/util/Decoupled.scala:286:19
  reg  [4:0] enq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg  [4:0] deq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg        maybe_full;	// src/main/scala/chisel3/util/Decoupled.scala:259:27
  wire       ptr_match = enq_ptr_value == deq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:260:33
  wire       do_enq = io_enq_ready & io_enq_valid;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :286:19
  assign io_enq_ready = ~(ptr_match & maybe_full);	// src/main/scala/chisel3/util/Decoupled.scala:259:27, :260:33, :262:24, :286:19
  always @(posedge clock) begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    if (reset) begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      enq_ptr_value <= 5'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
      deq_ptr_value <= 5'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
      maybe_full <= 1'h0;	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :259:27
    end
    else begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      automatic logic do_deq;	// src/main/scala/chisel3/util/Decoupled.scala:51:35
      do_deq = io_deq_ready & ~(ptr_match & ~maybe_full);	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27, :260:33, :261:{25,28}, :285:19
      if (do_enq) begin	// src/main/scala/chisel3/util/Decoupled.scala:51:35
        if (enq_ptr_value == 5'h19)	// src/main/scala/chisel3/util/Counter.scala:61:40, :73:24
          enq_ptr_value <= 5'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
        else	// src/main/scala/chisel3/util/Counter.scala:73:24
          enq_ptr_value <= enq_ptr_value + 5'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      end
      if (do_deq) begin	// src/main/scala/chisel3/util/Decoupled.scala:51:35
        if (deq_ptr_value == 5'h19)	// src/main/scala/chisel3/util/Counter.scala:61:40, :73:24
          deq_ptr_value <= 5'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
        else	// src/main/scala/chisel3/util/Counter.scala:73:24
          deq_ptr_value <= deq_ptr_value + 5'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      end
      if (~(do_enq == do_deq))	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27, :276:{15,27}, :277:16
        maybe_full <= do_enq;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      automatic logic [31:0] _RANDOM[0:0];	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Decoupled.scala:243:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/chisel3/util/Decoupled.scala:243:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/chisel3/util/Decoupled.scala:243:7
        enq_ptr_value = _RANDOM[/*Zero width*/ 1'b0][4:0];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:243:7
        deq_ptr_value = _RANDOM[/*Zero width*/ 1'b0][9:5];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:243:7
        maybe_full = _RANDOM[/*Zero width*/ 1'b0][10];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:243:7, :259:27
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ram_26x32 ram_ext (	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    .R0_addr (deq_ptr_value),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .R0_en   (1'h1),	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    .R0_clk  (clock),
    .R0_data (io_deq_bits),
    .W0_addr (enq_ptr_value),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .W0_en   (do_enq),	// src/main/scala/chisel3/util/Decoupled.scala:51:35
    .W0_clk  (clock),
    .W0_data (io_enq_bits)
  );
endmodule

module FIFO(	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:497:7
  input         clock,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:497:7
                reset,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:497:7
                io_enq_valid,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:498:14
  input  [31:0] io_enq_bits,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:498:14
  input         io_deq_ready,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:498:14
  output [31:0] io_deq_bits	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:498:14
);

  Queue26_UInt32 q (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:503:17
    .clock        (clock),
    .reset        (reset),
    .io_enq_valid (io_enq_valid),
    .io_enq_bits  (io_enq_bits),
    .io_deq_ready (io_deq_ready),
    .io_deq_bits  (io_deq_bits)
  );
endmodule

// VCS coverage exclude_file
module ram_20x32(	// src/main/scala/chisel3/util/Decoupled.scala:256:91
  input  [4:0]  R0_addr,
  input         R0_en,
                R0_clk,
  output [31:0] R0_data,
  input  [4:0]  W0_addr,
  input         W0_en,
                W0_clk,
  input  [31:0] W0_data
);

  reg [31:0] Memory[0:19];	// src/main/scala/chisel3/util/Decoupled.scala:256:91
  always @(posedge W0_clk) begin	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    if (W0_en & 1'h1)	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      Memory[W0_addr] <= W0_data;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    reg [31:0] _RANDOM_MEM;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    initial begin	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      `INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      `ifdef RANDOMIZE_MEM_INIT	// src/main/scala/chisel3/util/Decoupled.scala:256:91
        for (logic [4:0] i = 5'h0; i < 5'h14; i += 5'h1) begin
          _RANDOM_MEM = `RANDOM;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
          Memory[i] = _RANDOM_MEM;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
        end	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 32'bx;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
endmodule

module Queue20_UInt32(	// src/main/scala/chisel3/util/Decoupled.scala:243:7
  input         clock,	// src/main/scala/chisel3/util/Decoupled.scala:243:7
                reset,	// src/main/scala/chisel3/util/Decoupled.scala:243:7
                io_enq_valid,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input  [31:0] io_enq_bits,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input         io_deq_ready,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  output [31:0] io_deq_bits	// src/main/scala/chisel3/util/Decoupled.scala:255:14
);

  wire       io_enq_ready;	// src/main/scala/chisel3/util/Decoupled.scala:286:19
  reg  [4:0] enq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg  [4:0] deq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg        maybe_full;	// src/main/scala/chisel3/util/Decoupled.scala:259:27
  wire       ptr_match = enq_ptr_value == deq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:260:33
  wire       do_enq = io_enq_ready & io_enq_valid;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :286:19
  assign io_enq_ready = ~(ptr_match & maybe_full);	// src/main/scala/chisel3/util/Decoupled.scala:259:27, :260:33, :262:24, :286:19
  always @(posedge clock) begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    if (reset) begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      enq_ptr_value <= 5'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
      deq_ptr_value <= 5'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
      maybe_full <= 1'h0;	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :259:27
    end
    else begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      automatic logic do_deq;	// src/main/scala/chisel3/util/Decoupled.scala:51:35
      do_deq = io_deq_ready & ~(ptr_match & ~maybe_full);	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27, :260:33, :261:{25,28}, :285:19
      if (do_enq) begin	// src/main/scala/chisel3/util/Decoupled.scala:51:35
        if (enq_ptr_value == 5'h13)	// src/main/scala/chisel3/util/Counter.scala:61:40, :73:24
          enq_ptr_value <= 5'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
        else	// src/main/scala/chisel3/util/Counter.scala:73:24
          enq_ptr_value <= enq_ptr_value + 5'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      end
      if (do_deq) begin	// src/main/scala/chisel3/util/Decoupled.scala:51:35
        if (deq_ptr_value == 5'h13)	// src/main/scala/chisel3/util/Counter.scala:61:40, :73:24
          deq_ptr_value <= 5'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
        else	// src/main/scala/chisel3/util/Counter.scala:73:24
          deq_ptr_value <= deq_ptr_value + 5'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      end
      if (~(do_enq == do_deq))	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27, :276:{15,27}, :277:16
        maybe_full <= do_enq;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      automatic logic [31:0] _RANDOM[0:0];	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Decoupled.scala:243:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/chisel3/util/Decoupled.scala:243:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/chisel3/util/Decoupled.scala:243:7
        enq_ptr_value = _RANDOM[/*Zero width*/ 1'b0][4:0];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:243:7
        deq_ptr_value = _RANDOM[/*Zero width*/ 1'b0][9:5];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:243:7
        maybe_full = _RANDOM[/*Zero width*/ 1'b0][10];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:243:7, :259:27
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ram_20x32 ram_ext (	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    .R0_addr (deq_ptr_value),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .R0_en   (1'h1),	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    .R0_clk  (clock),
    .R0_data (io_deq_bits),
    .W0_addr (enq_ptr_value),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .W0_en   (do_enq),	// src/main/scala/chisel3/util/Decoupled.scala:51:35
    .W0_clk  (clock),
    .W0_data (io_enq_bits)
  );
endmodule

module FIFO_1(	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:497:7
  input         clock,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:497:7
                reset,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:497:7
                io_enq_valid,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:498:14
  input  [31:0] io_enq_bits,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:498:14
  input         io_deq_ready,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:498:14
  output [31:0] io_deq_bits	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:498:14
);

  Queue20_UInt32 q (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:503:17
    .clock        (clock),
    .reset        (reset),
    .io_enq_valid (io_enq_valid),
    .io_enq_bits  (io_enq_bits),
    .io_deq_ready (io_deq_ready),
    .io_deq_bits  (io_deq_bits)
  );
endmodule

// VCS coverage exclude_file
module ram_15x32(	// src/main/scala/chisel3/util/Decoupled.scala:256:91
  input  [3:0]  R0_addr,
  input         R0_en,
                R0_clk,
  output [31:0] R0_data,
  input  [3:0]  W0_addr,
  input         W0_en,
                W0_clk,
  input  [31:0] W0_data
);

  reg [31:0] Memory[0:14];	// src/main/scala/chisel3/util/Decoupled.scala:256:91
  always @(posedge W0_clk) begin	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    if (W0_en & 1'h1)	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      Memory[W0_addr] <= W0_data;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    reg [31:0] _RANDOM_MEM;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    initial begin	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      `INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      `ifdef RANDOMIZE_MEM_INIT	// src/main/scala/chisel3/util/Decoupled.scala:256:91
        for (logic [3:0] i = 4'h0; i < 4'hF; i += 4'h1) begin
          _RANDOM_MEM = `RANDOM;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
          Memory[i] = _RANDOM_MEM;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
        end	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 32'bx;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
endmodule

module Queue15_UInt32(	// src/main/scala/chisel3/util/Decoupled.scala:243:7
  input         clock,	// src/main/scala/chisel3/util/Decoupled.scala:243:7
                reset,	// src/main/scala/chisel3/util/Decoupled.scala:243:7
                io_enq_valid,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input  [31:0] io_enq_bits,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input         io_deq_ready,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  output [31:0] io_deq_bits	// src/main/scala/chisel3/util/Decoupled.scala:255:14
);

  wire       io_enq_ready;	// src/main/scala/chisel3/util/Decoupled.scala:286:19
  reg  [3:0] enq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg  [3:0] deq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg        maybe_full;	// src/main/scala/chisel3/util/Decoupled.scala:259:27
  wire       ptr_match = enq_ptr_value == deq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:260:33
  wire       do_enq = io_enq_ready & io_enq_valid;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :286:19
  assign io_enq_ready = ~(ptr_match & maybe_full);	// src/main/scala/chisel3/util/Decoupled.scala:259:27, :260:33, :262:24, :286:19
  always @(posedge clock) begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    if (reset) begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      enq_ptr_value <= 4'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
      deq_ptr_value <= 4'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
      maybe_full <= 1'h0;	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :259:27
    end
    else begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      automatic logic do_deq;	// src/main/scala/chisel3/util/Decoupled.scala:51:35
      do_deq = io_deq_ready & ~(ptr_match & ~maybe_full);	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27, :260:33, :261:{25,28}, :285:19
      if (do_enq) begin	// src/main/scala/chisel3/util/Decoupled.scala:51:35
        if (enq_ptr_value == 4'hE)	// src/main/scala/chisel3/util/Counter.scala:61:40, :73:24
          enq_ptr_value <= 4'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
        else	// src/main/scala/chisel3/util/Counter.scala:73:24
          enq_ptr_value <= enq_ptr_value + 4'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      end
      if (do_deq) begin	// src/main/scala/chisel3/util/Decoupled.scala:51:35
        if (deq_ptr_value == 4'hE)	// src/main/scala/chisel3/util/Counter.scala:61:40, :73:24
          deq_ptr_value <= 4'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
        else	// src/main/scala/chisel3/util/Counter.scala:73:24
          deq_ptr_value <= deq_ptr_value + 4'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      end
      if (~(do_enq == do_deq))	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27, :276:{15,27}, :277:16
        maybe_full <= do_enq;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      automatic logic [31:0] _RANDOM[0:0];	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Decoupled.scala:243:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/chisel3/util/Decoupled.scala:243:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/chisel3/util/Decoupled.scala:243:7
        enq_ptr_value = _RANDOM[/*Zero width*/ 1'b0][3:0];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:243:7
        deq_ptr_value = _RANDOM[/*Zero width*/ 1'b0][7:4];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:243:7
        maybe_full = _RANDOM[/*Zero width*/ 1'b0][8];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:243:7, :259:27
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ram_15x32 ram_ext (	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    .R0_addr (deq_ptr_value),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .R0_en   (1'h1),	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    .R0_clk  (clock),
    .R0_data (io_deq_bits),
    .W0_addr (enq_ptr_value),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .W0_en   (do_enq),	// src/main/scala/chisel3/util/Decoupled.scala:51:35
    .W0_clk  (clock),
    .W0_data (io_enq_bits)
  );
endmodule

module FIFO_2(	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:497:7
  input         clock,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:497:7
                reset,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:497:7
                io_enq_valid,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:498:14
  input  [31:0] io_enq_bits,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:498:14
  input         io_deq_ready,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:498:14
  output [31:0] io_deq_bits	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:498:14
);

  Queue15_UInt32 q (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:503:17
    .clock        (clock),
    .reset        (reset),
    .io_enq_valid (io_enq_valid),
    .io_enq_bits  (io_enq_bits),
    .io_deq_ready (io_deq_ready),
    .io_deq_bits  (io_deq_bits)
  );
endmodule

// VCS coverage exclude_file
module ram_11x32(	// src/main/scala/chisel3/util/Decoupled.scala:256:91
  input  [3:0]  R0_addr,
  input         R0_en,
                R0_clk,
  output [31:0] R0_data,
  input  [3:0]  W0_addr,
  input         W0_en,
                W0_clk,
  input  [31:0] W0_data
);

  reg [31:0] Memory[0:10];	// src/main/scala/chisel3/util/Decoupled.scala:256:91
  always @(posedge W0_clk) begin	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    if (W0_en & 1'h1)	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      Memory[W0_addr] <= W0_data;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    reg [31:0] _RANDOM_MEM;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    initial begin	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      `INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      `ifdef RANDOMIZE_MEM_INIT	// src/main/scala/chisel3/util/Decoupled.scala:256:91
        for (logic [3:0] i = 4'h0; i < 4'hB; i += 4'h1) begin
          _RANDOM_MEM = `RANDOM;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
          Memory[i] = _RANDOM_MEM;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
        end	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 32'bx;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
endmodule

module Queue11_UInt32(	// src/main/scala/chisel3/util/Decoupled.scala:243:7
  input         clock,	// src/main/scala/chisel3/util/Decoupled.scala:243:7
                reset,	// src/main/scala/chisel3/util/Decoupled.scala:243:7
                io_enq_valid,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input  [31:0] io_enq_bits,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input         io_deq_ready,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  output [31:0] io_deq_bits	// src/main/scala/chisel3/util/Decoupled.scala:255:14
);

  wire       io_enq_ready;	// src/main/scala/chisel3/util/Decoupled.scala:286:19
  reg  [3:0] enq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg  [3:0] deq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg        maybe_full;	// src/main/scala/chisel3/util/Decoupled.scala:259:27
  wire       ptr_match = enq_ptr_value == deq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:260:33
  wire       do_enq = io_enq_ready & io_enq_valid;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :286:19
  assign io_enq_ready = ~(ptr_match & maybe_full);	// src/main/scala/chisel3/util/Decoupled.scala:259:27, :260:33, :262:24, :286:19
  always @(posedge clock) begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    if (reset) begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      enq_ptr_value <= 4'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
      deq_ptr_value <= 4'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
      maybe_full <= 1'h0;	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :259:27
    end
    else begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      automatic logic do_deq;	// src/main/scala/chisel3/util/Decoupled.scala:51:35
      do_deq = io_deq_ready & ~(ptr_match & ~maybe_full);	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27, :260:33, :261:{25,28}, :285:19
      if (do_enq) begin	// src/main/scala/chisel3/util/Decoupled.scala:51:35
        if (enq_ptr_value == 4'hA)	// src/main/scala/chisel3/util/Counter.scala:61:40, :73:24
          enq_ptr_value <= 4'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
        else	// src/main/scala/chisel3/util/Counter.scala:73:24
          enq_ptr_value <= enq_ptr_value + 4'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      end
      if (do_deq) begin	// src/main/scala/chisel3/util/Decoupled.scala:51:35
        if (deq_ptr_value == 4'hA)	// src/main/scala/chisel3/util/Counter.scala:61:40, :73:24
          deq_ptr_value <= 4'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
        else	// src/main/scala/chisel3/util/Counter.scala:73:24
          deq_ptr_value <= deq_ptr_value + 4'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      end
      if (~(do_enq == do_deq))	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27, :276:{15,27}, :277:16
        maybe_full <= do_enq;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      automatic logic [31:0] _RANDOM[0:0];	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Decoupled.scala:243:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/chisel3/util/Decoupled.scala:243:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/chisel3/util/Decoupled.scala:243:7
        enq_ptr_value = _RANDOM[/*Zero width*/ 1'b0][3:0];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:243:7
        deq_ptr_value = _RANDOM[/*Zero width*/ 1'b0][7:4];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:243:7
        maybe_full = _RANDOM[/*Zero width*/ 1'b0][8];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:243:7, :259:27
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ram_11x32 ram_ext (	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    .R0_addr (deq_ptr_value),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .R0_en   (1'h1),	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    .R0_clk  (clock),
    .R0_data (io_deq_bits),
    .W0_addr (enq_ptr_value),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .W0_en   (do_enq),	// src/main/scala/chisel3/util/Decoupled.scala:51:35
    .W0_clk  (clock),
    .W0_data (io_enq_bits)
  );
endmodule

module FIFO_3(	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:497:7
  input         clock,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:497:7
                reset,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:497:7
                io_enq_valid,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:498:14
  input  [31:0] io_enq_bits,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:498:14
  input         io_deq_ready,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:498:14
  output [31:0] io_deq_bits	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:498:14
);

  Queue11_UInt32 q (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:503:17
    .clock        (clock),
    .reset        (reset),
    .io_enq_valid (io_enq_valid),
    .io_enq_bits  (io_enq_bits),
    .io_deq_ready (io_deq_ready),
    .io_deq_bits  (io_deq_bits)
  );
endmodule

// VCS coverage exclude_file
module ram_7x32(	// src/main/scala/chisel3/util/Decoupled.scala:256:91
  input  [2:0]  R0_addr,
  input         R0_en,
                R0_clk,
  output [31:0] R0_data,
  input  [2:0]  W0_addr,
  input         W0_en,
                W0_clk,
  input  [31:0] W0_data
);

  reg [31:0] Memory[0:6];	// src/main/scala/chisel3/util/Decoupled.scala:256:91
  always @(posedge W0_clk) begin	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    if (W0_en & 1'h1)	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      Memory[W0_addr] <= W0_data;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    reg [31:0] _RANDOM_MEM;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    initial begin	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      `INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      `ifdef RANDOMIZE_MEM_INIT	// src/main/scala/chisel3/util/Decoupled.scala:256:91
        for (logic [2:0] i = 3'h0; i < 3'h7; i += 3'h1) begin
          _RANDOM_MEM = `RANDOM;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
          Memory[i] = _RANDOM_MEM;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
        end	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 32'bx;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
endmodule

module Queue7_UInt32(	// src/main/scala/chisel3/util/Decoupled.scala:243:7
  input         clock,	// src/main/scala/chisel3/util/Decoupled.scala:243:7
                reset,	// src/main/scala/chisel3/util/Decoupled.scala:243:7
                io_enq_valid,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input  [31:0] io_enq_bits,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input         io_deq_ready,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  output [31:0] io_deq_bits	// src/main/scala/chisel3/util/Decoupled.scala:255:14
);

  wire       io_enq_ready;	// src/main/scala/chisel3/util/Decoupled.scala:286:19
  reg  [2:0] enq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg  [2:0] deq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg        maybe_full;	// src/main/scala/chisel3/util/Decoupled.scala:259:27
  wire       ptr_match = enq_ptr_value == deq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:260:33
  wire       do_enq = io_enq_ready & io_enq_valid;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :286:19
  assign io_enq_ready = ~(ptr_match & maybe_full);	// src/main/scala/chisel3/util/Decoupled.scala:259:27, :260:33, :262:24, :286:19
  always @(posedge clock) begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    if (reset) begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      enq_ptr_value <= 3'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
      deq_ptr_value <= 3'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
      maybe_full <= 1'h0;	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :259:27
    end
    else begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      automatic logic do_deq;	// src/main/scala/chisel3/util/Decoupled.scala:51:35
      do_deq = io_deq_ready & ~(ptr_match & ~maybe_full);	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27, :260:33, :261:{25,28}, :285:19
      if (do_enq) begin	// src/main/scala/chisel3/util/Decoupled.scala:51:35
        if (enq_ptr_value == 3'h6)	// src/main/scala/chisel3/util/Counter.scala:61:40, :73:24
          enq_ptr_value <= 3'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
        else	// src/main/scala/chisel3/util/Counter.scala:73:24
          enq_ptr_value <= enq_ptr_value + 3'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      end
      if (do_deq) begin	// src/main/scala/chisel3/util/Decoupled.scala:51:35
        if (deq_ptr_value == 3'h6)	// src/main/scala/chisel3/util/Counter.scala:61:40, :73:24
          deq_ptr_value <= 3'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
        else	// src/main/scala/chisel3/util/Counter.scala:73:24
          deq_ptr_value <= deq_ptr_value + 3'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      end
      if (~(do_enq == do_deq))	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27, :276:{15,27}, :277:16
        maybe_full <= do_enq;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      automatic logic [31:0] _RANDOM[0:0];	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Decoupled.scala:243:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/chisel3/util/Decoupled.scala:243:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/chisel3/util/Decoupled.scala:243:7
        enq_ptr_value = _RANDOM[/*Zero width*/ 1'b0][2:0];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:243:7
        deq_ptr_value = _RANDOM[/*Zero width*/ 1'b0][5:3];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:243:7
        maybe_full = _RANDOM[/*Zero width*/ 1'b0][6];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:243:7, :259:27
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ram_7x32 ram_ext (	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    .R0_addr (deq_ptr_value),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .R0_en   (1'h1),	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    .R0_clk  (clock),
    .R0_data (io_deq_bits),
    .W0_addr (enq_ptr_value),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .W0_en   (do_enq),	// src/main/scala/chisel3/util/Decoupled.scala:51:35
    .W0_clk  (clock),
    .W0_data (io_enq_bits)
  );
endmodule

module FIFO_4(	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:497:7
  input         clock,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:497:7
                reset,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:497:7
                io_enq_valid,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:498:14
  input  [31:0] io_enq_bits,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:498:14
  input         io_deq_ready,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:498:14
  output [31:0] io_deq_bits	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:498:14
);

  Queue7_UInt32 q (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:503:17
    .clock        (clock),
    .reset        (reset),
    .io_enq_valid (io_enq_valid),
    .io_enq_bits  (io_enq_bits),
    .io_deq_ready (io_deq_ready),
    .io_deq_bits  (io_deq_bits)
  );
endmodule

// VCS coverage exclude_file
module ram_5x32(	// src/main/scala/chisel3/util/Decoupled.scala:256:91
  input  [2:0]  R0_addr,
  input         R0_en,
                R0_clk,
  output [31:0] R0_data,
  input  [2:0]  W0_addr,
  input         W0_en,
                W0_clk,
  input  [31:0] W0_data
);

  reg [31:0] Memory[0:4];	// src/main/scala/chisel3/util/Decoupled.scala:256:91
  always @(posedge W0_clk) begin	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    if (W0_en & 1'h1)	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      Memory[W0_addr] <= W0_data;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    reg [31:0] _RANDOM_MEM;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    initial begin	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      `INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      `ifdef RANDOMIZE_MEM_INIT	// src/main/scala/chisel3/util/Decoupled.scala:256:91
        for (logic [2:0] i = 3'h0; i < 3'h5; i += 3'h1) begin
          _RANDOM_MEM = `RANDOM;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
          Memory[i] = _RANDOM_MEM;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
        end	// src/main/scala/chisel3/util/Decoupled.scala:256:91
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 32'bx;	// src/main/scala/chisel3/util/Decoupled.scala:256:91
endmodule

module Queue5_UInt32(	// src/main/scala/chisel3/util/Decoupled.scala:243:7
  input         clock,	// src/main/scala/chisel3/util/Decoupled.scala:243:7
                reset,	// src/main/scala/chisel3/util/Decoupled.scala:243:7
                io_enq_valid,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input  [31:0] io_enq_bits,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  input         io_deq_ready,	// src/main/scala/chisel3/util/Decoupled.scala:255:14
  output [31:0] io_deq_bits	// src/main/scala/chisel3/util/Decoupled.scala:255:14
);

  wire       io_enq_ready;	// src/main/scala/chisel3/util/Decoupled.scala:286:19
  reg  [2:0] enq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg  [2:0] deq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg        maybe_full;	// src/main/scala/chisel3/util/Decoupled.scala:259:27
  wire       ptr_match = enq_ptr_value == deq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:260:33
  wire       do_enq = io_enq_ready & io_enq_valid;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :286:19
  assign io_enq_ready = ~(ptr_match & maybe_full);	// src/main/scala/chisel3/util/Decoupled.scala:259:27, :260:33, :262:24, :286:19
  always @(posedge clock) begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    if (reset) begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      enq_ptr_value <= 3'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
      deq_ptr_value <= 3'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
      maybe_full <= 1'h0;	// src/main/scala/chisel3/util/Decoupled.scala:243:7, :259:27
    end
    else begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      automatic logic do_deq;	// src/main/scala/chisel3/util/Decoupled.scala:51:35
      do_deq = io_deq_ready & ~(ptr_match & ~maybe_full);	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27, :260:33, :261:{25,28}, :285:19
      if (do_enq) begin	// src/main/scala/chisel3/util/Decoupled.scala:51:35
        if (enq_ptr_value == 3'h4)	// src/main/scala/chisel3/util/Counter.scala:61:40, :73:24
          enq_ptr_value <= 3'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
        else	// src/main/scala/chisel3/util/Counter.scala:73:24
          enq_ptr_value <= enq_ptr_value + 3'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      end
      if (do_deq) begin	// src/main/scala/chisel3/util/Decoupled.scala:51:35
        if (deq_ptr_value == 3'h4)	// src/main/scala/chisel3/util/Counter.scala:61:40, :73:24
          deq_ptr_value <= 3'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
        else	// src/main/scala/chisel3/util/Counter.scala:73:24
          deq_ptr_value <= deq_ptr_value + 3'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      end
      if (~(do_enq == do_deq))	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27, :276:{15,27}, :277:16
        maybe_full <= do_enq;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      automatic logic [31:0] _RANDOM[0:0];	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Decoupled.scala:243:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/chisel3/util/Decoupled.scala:243:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/chisel3/util/Decoupled.scala:243:7
        enq_ptr_value = _RANDOM[/*Zero width*/ 1'b0][2:0];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:243:7
        deq_ptr_value = _RANDOM[/*Zero width*/ 1'b0][5:3];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:243:7
        maybe_full = _RANDOM[/*Zero width*/ 1'b0][6];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:243:7, :259:27
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ram_5x32 ram_ext (	// src/main/scala/chisel3/util/Decoupled.scala:256:91
    .R0_addr (deq_ptr_value),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .R0_en   (1'h1),	// src/main/scala/chisel3/util/Decoupled.scala:243:7
    .R0_clk  (clock),
    .R0_data (io_deq_bits),
    .W0_addr (enq_ptr_value),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .W0_en   (do_enq),	// src/main/scala/chisel3/util/Decoupled.scala:51:35
    .W0_clk  (clock),
    .W0_data (io_enq_bits)
  );
endmodule

module FIFO_5(	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:497:7
  input         clock,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:497:7
                reset,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:497:7
                io_enq_valid,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:498:14
  input  [31:0] io_enq_bits,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:498:14
  input         io_deq_ready,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:498:14
  output [31:0] io_deq_bits	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:498:14
);

  Queue5_UInt32 q (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:503:17
    .clock        (clock),
    .reset        (reset),
    .io_enq_valid (io_enq_valid),
    .io_enq_bits  (io_enq_bits),
    .io_deq_ready (io_deq_ready),
    .io_deq_bits  (io_deq_bits)
  );
endmodule

module laplace_3d(	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:62:7
  input          clock,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:62:7
                 reset,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:62:7
  input  [287:0] io_datapath_data_in,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:63:14
  input          io_datapath_ready_in,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:63:14
  output [31:0]  io_datapath_data_out1,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:63:14
                 io_datapath_data_out2,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:63:14
                 io_datapath_data_out3,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:63:14
                 io_datapath_data_out4,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:63:14
                 io_datapath_data_out5,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:63:14
                 io_datapath_data_out6	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:63:14
);

  wire        _Filter_3d_5_io_valid_out;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:97:18
  wire [31:0] _Filter_3d_5_io_data_to_Fifo;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:97:18
  wire        _Filter_3d_4_io_valid_out;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:96:18
  wire [31:0] _Filter_3d_4_io_data_to_Fifo;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:96:18
  wire [31:0] _Filter_3d_4_io_data_to_rebuffer_4;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:96:18
  wire        _Filter_3d_3_io_valid_out;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:95:18
  wire [31:0] _Filter_3d_3_io_data_to_Fifo;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:95:18
  wire [31:0] _Filter_3d_3_io_data_to_rebuffer_4;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:95:18
  wire [31:0] _Filter_3d_3_io_data_to_rebuffer_7;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:95:18
  wire        _Filter_3d_2_io_valid_out;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:94:18
  wire [31:0] _Filter_3d_2_io_data_to_Fifo;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:94:18
  wire [31:0] _Filter_3d_2_io_data_to_rebuffer_4;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:94:18
  wire [31:0] _Filter_3d_2_io_data_to_rebuffer_5;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:94:18
  wire [31:0] _Filter_3d_2_io_data_to_rebuffer_7;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:94:18
  wire        _Filter_3d_1_io_valid_out;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:93:18
  wire [31:0] _Filter_3d_1_io_data_to_Fifo;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:93:18
  wire [31:0] _Filter_3d_1_io_data_to_rebuffer_3;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:93:18
  wire [31:0] _Filter_3d_1_io_data_to_rebuffer_4;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:93:18
  wire [31:0] _Filter_3d_1_io_data_to_rebuffer_5;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:93:18
  wire [31:0] _Filter_3d_1_io_data_to_rebuffer_7;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:93:18
  wire        _Filter_3d_io_valid_out;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:92:18
  wire [31:0] _Filter_3d_io_data_to_Fifo;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:92:18
  wire [31:0] _Filter_3d_io_data_to_rebuffer_1;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:92:18
  wire [31:0] _Filter_3d_io_data_to_rebuffer_3;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:92:18
  wire [31:0] _Filter_3d_io_data_to_rebuffer_4;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:92:18
  wire [31:0] _Filter_3d_io_data_to_rebuffer_5;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:92:18
  wire [31:0] _Filter_3d_io_data_to_rebuffer_7;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:92:18
  reg  [31:0] z_cnt;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:80:22
  reg  [31:0] cnt;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:82:20
  reg         f1_deq;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:162:23
  reg         f2_deq;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:163:23
  reg         f3_deq;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:164:23
  reg         f4_deq;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:165:23
  reg         f5_deq;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:166:23
  reg         f6_deq;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:167:23
  always @(posedge clock) begin	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:62:7
    if (reset) begin	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:62:7
      z_cnt <= 32'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:80:22
      cnt <= 32'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:80:22, :82:20
      f1_deq <= 1'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:87:11, :162:23
      f2_deq <= 1'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:87:11, :163:23
      f3_deq <= 1'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:87:11, :164:23
      f4_deq <= 1'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:87:11, :165:23
      f5_deq <= 1'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:87:11, :166:23
      f6_deq <= 1'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:87:11, :167:23
    end
    else begin	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:62:7
      automatic logic _GEN;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:169:12
      _GEN = cnt == 32'h15;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:82:20, :169:12
      if (z_cnt == 32'h6)	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:80:22, :86:15
        z_cnt <= 32'h0;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:80:22
      else	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:86:15
        z_cnt <= z_cnt + 32'h1;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:80:22, :84:12, :89:20
      cnt <= cnt + 32'h1;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:82:20, :84:12
      f1_deq <= _GEN | f1_deq;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:162:23, :169:{12,21}, :170:12
      f2_deq <= _GEN | f2_deq;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:163:23, :169:{12,21}, :172:12
      f3_deq <= _GEN | f3_deq;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:164:23, :169:{12,21}, :174:12
      f4_deq <= _GEN | f4_deq;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:165:23, :169:{12,21}, :176:12
      f5_deq <= _GEN | f5_deq;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:166:23, :169:{12,21}, :178:12
      f6_deq <= _GEN | f6_deq;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:167:23, :169:{12,21}, :180:12
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:62:7
    `ifdef FIRRTL_BEFORE_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:62:7
      `FIRRTL_BEFORE_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:62:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:62:7
      automatic logic [31:0] _RANDOM[0:2];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:62:7
      `ifdef INIT_RANDOM_PROLOG_	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:62:7
        `INIT_RANDOM_PROLOG_	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:62:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:62:7
        for (logic [1:0] i = 2'h0; i < 2'h3; i += 2'h1) begin
          _RANDOM[i] = `RANDOM;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:62:7
        end	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:62:7
        z_cnt = _RANDOM[2'h0];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:62:7, :80:22
        cnt = _RANDOM[2'h1];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:62:7, :82:20
        f1_deq = _RANDOM[2'h2][0];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:62:7, :162:23
        f2_deq = _RANDOM[2'h2][1];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:62:7, :162:23, :163:23
        f3_deq = _RANDOM[2'h2][2];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:62:7, :162:23, :164:23
        f4_deq = _RANDOM[2'h2][3];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:62:7, :162:23, :165:23
        f5_deq = _RANDOM[2'h2][4];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:62:7, :162:23, :166:23
        f6_deq = _RANDOM[2'h2][5];	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:62:7, :162:23, :167:23
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:62:7
      `FIRRTL_AFTER_INITIAL	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:62:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  Filter_3d Filter_3d (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:92:18
    .clock                 (clock),
    .reset                 (reset),
    .io_data_in_1          (io_datapath_data_in[255:224]),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:112:41
    .io_data_in_3          (io_datapath_data_in[191:160]),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:112:41
    .io_data_in_4          (io_datapath_data_in[159:128]),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:112:41
    .io_data_in_5          (io_datapath_data_in[127:96]),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:112:41
    .io_data_in_7          (io_datapath_data_in[63:32]),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:112:41
    .io_valid_out          (_Filter_3d_io_valid_out),
    .io_data_to_Fifo       (_Filter_3d_io_data_to_Fifo),
    .io_data_to_rebuffer_1 (_Filter_3d_io_data_to_rebuffer_1),
    .io_data_to_rebuffer_3 (_Filter_3d_io_data_to_rebuffer_3),
    .io_data_to_rebuffer_4 (_Filter_3d_io_data_to_rebuffer_4),
    .io_data_to_rebuffer_5 (_Filter_3d_io_data_to_rebuffer_5),
    .io_data_to_rebuffer_7 (_Filter_3d_io_data_to_rebuffer_7)
  );
  Filter_3d_1 Filter_3d_1 (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:93:18
    .clock                 (clock),
    .reset                 (reset),
    .io_data_in_1          (_Filter_3d_io_data_to_rebuffer_1),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:92:18
    .io_data_in_3          (_Filter_3d_io_data_to_rebuffer_3),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:92:18
    .io_data_in_4          (_Filter_3d_io_data_to_rebuffer_4),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:92:18
    .io_data_in_5          (_Filter_3d_io_data_to_rebuffer_5),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:92:18
    .io_data_in_7          (_Filter_3d_io_data_to_rebuffer_7),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:92:18
    .io_valid_out          (_Filter_3d_1_io_valid_out),
    .io_data_to_Fifo       (_Filter_3d_1_io_data_to_Fifo),
    .io_data_to_rebuffer_3 (_Filter_3d_1_io_data_to_rebuffer_3),
    .io_data_to_rebuffer_4 (_Filter_3d_1_io_data_to_rebuffer_4),
    .io_data_to_rebuffer_5 (_Filter_3d_1_io_data_to_rebuffer_5),
    .io_data_to_rebuffer_7 (_Filter_3d_1_io_data_to_rebuffer_7)
  );
  Filter_3d_2 Filter_3d_2 (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:94:18
    .clock                 (clock),
    .reset                 (reset),
    .io_data_in_3          (_Filter_3d_1_io_data_to_rebuffer_3),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:93:18
    .io_data_in_4          (_Filter_3d_1_io_data_to_rebuffer_4),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:93:18
    .io_data_in_5          (_Filter_3d_1_io_data_to_rebuffer_5),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:93:18
    .io_data_in_7          (_Filter_3d_1_io_data_to_rebuffer_7),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:93:18
    .io_valid_out          (_Filter_3d_2_io_valid_out),
    .io_data_to_Fifo       (_Filter_3d_2_io_data_to_Fifo),
    .io_data_to_rebuffer_4 (_Filter_3d_2_io_data_to_rebuffer_4),
    .io_data_to_rebuffer_5 (_Filter_3d_2_io_data_to_rebuffer_5),
    .io_data_to_rebuffer_7 (_Filter_3d_2_io_data_to_rebuffer_7)
  );
  Filter_3d_3 Filter_3d_3 (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:95:18
    .clock                 (clock),
    .reset                 (reset),
    .io_data_in_4          (_Filter_3d_2_io_data_to_rebuffer_4),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:94:18
    .io_data_in_5          (_Filter_3d_2_io_data_to_rebuffer_5),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:94:18
    .io_data_in_7          (_Filter_3d_2_io_data_to_rebuffer_7),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:94:18
    .io_valid_out          (_Filter_3d_3_io_valid_out),
    .io_data_to_Fifo       (_Filter_3d_3_io_data_to_Fifo),
    .io_data_to_rebuffer_4 (_Filter_3d_3_io_data_to_rebuffer_4),
    .io_data_to_rebuffer_7 (_Filter_3d_3_io_data_to_rebuffer_7)
  );
  Filter_3d_4 Filter_3d_4 (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:96:18
    .clock                 (clock),
    .reset                 (reset),
    .io_data_in_4          (_Filter_3d_3_io_data_to_rebuffer_4),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:95:18
    .io_data_in_7          (_Filter_3d_3_io_data_to_rebuffer_7),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:95:18
    .io_valid_out          (_Filter_3d_4_io_valid_out),
    .io_data_to_Fifo       (_Filter_3d_4_io_data_to_Fifo),
    .io_data_to_rebuffer_4 (_Filter_3d_4_io_data_to_rebuffer_4)
  );
  Filter_3d_5 Filter_3d_5 (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:97:18
    .clock           (clock),
    .reset           (reset),
    .io_data_in_4    (_Filter_3d_4_io_data_to_rebuffer_4),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:96:18
    .io_valid_out    (_Filter_3d_5_io_valid_out),
    .io_data_to_Fifo (_Filter_3d_5_io_data_to_Fifo)
  );
  FIFO fifo1 (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:129:22
    .clock        (clock),
    .reset        (reset),
    .io_enq_valid (_Filter_3d_io_valid_out),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:92:18
    .io_enq_bits  (_Filter_3d_io_data_to_Fifo),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:92:18
    .io_deq_ready (f1_deq),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:162:23
    .io_deq_bits  (io_datapath_data_out1)
  );
  FIFO_1 fifo2 (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:130:22
    .clock        (clock),
    .reset        (reset),
    .io_enq_valid (_Filter_3d_1_io_valid_out),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:93:18
    .io_enq_bits  (_Filter_3d_1_io_data_to_Fifo),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:93:18
    .io_deq_ready (f2_deq),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:163:23
    .io_deq_bits  (io_datapath_data_out2)
  );
  FIFO_2 fifo3 (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:131:22
    .clock        (clock),
    .reset        (reset),
    .io_enq_valid (_Filter_3d_2_io_valid_out),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:94:18
    .io_enq_bits  (_Filter_3d_2_io_data_to_Fifo),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:94:18
    .io_deq_ready (f3_deq),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:164:23
    .io_deq_bits  (io_datapath_data_out3)
  );
  FIFO_3 fifo4 (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:132:22
    .clock        (clock),
    .reset        (reset),
    .io_enq_valid (_Filter_3d_3_io_valid_out),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:95:18
    .io_enq_bits  (_Filter_3d_3_io_data_to_Fifo),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:95:18
    .io_deq_ready (f4_deq),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:165:23
    .io_deq_bits  (io_datapath_data_out4)
  );
  FIFO_4 fifo5 (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:133:22
    .clock        (clock),
    .reset        (reset),
    .io_enq_valid (_Filter_3d_4_io_valid_out),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:96:18
    .io_enq_bits  (_Filter_3d_4_io_data_to_Fifo),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:96:18
    .io_deq_ready (f5_deq),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:166:23
    .io_deq_bits  (io_datapath_data_out5)
  );
  FIFO_5 fifo6 (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:134:22
    .clock        (clock),
    .reset        (reset),
    .io_enq_valid (_Filter_3d_5_io_valid_out),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:97:18
    .io_enq_bits  (_Filter_3d_5_io_data_to_Fifo),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:97:18
    .io_deq_ready (f6_deq),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\stencil_2d.scala:167:23
    .io_deq_bits  (io_datapath_data_out6)
  );
endmodule


