// Generated by CIRCT firtool-1.62.0
// external module FP_mult

// external module FP_adder

module dot(	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:34:9
  input         clock,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:34:9
                reset,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:34:9
  input  [31:0] io_in_a_0,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:36:17
                io_in_a_1,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:36:17
                io_in_a_2,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:36:17
                io_in_a_3,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:36:17
                io_in_a_4,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:36:17
                io_in_a_5,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:36:17
                io_in_a_6,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:36:17
                io_in_a_7,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:36:17
                io_in_b_0,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:36:17
                io_in_b_1,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:36:17
                io_in_b_2,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:36:17
                io_in_b_3,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:36:17
                io_in_b_4,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:36:17
                io_in_b_5,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:36:17
                io_in_b_6,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:36:17
                io_in_b_7,	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:36:17
  output [31:0] io_out_s	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:36:17
);

  wire [31:0] _FP_adder_5_m_axis_result_tdata;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:62:21
  wire [31:0] _FP_adder_4_m_axis_result_tdata;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:62:21
  wire [31:0] _FP_adder_3_m_axis_result_tdata;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:62:21
  wire [31:0] _FP_adder_2_m_axis_result_tdata;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:62:21
  wire [31:0] _FP_adder_1_m_axis_result_tdata;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:62:21
  wire [31:0] _FP_adder_m_axis_result_tdata;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:62:21
  wire [31:0] _FP_mult_7_m_axis_result_tdata;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:50:21
  wire [31:0] _FP_mult_6_m_axis_result_tdata;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:50:21
  wire [31:0] _FP_mult_5_m_axis_result_tdata;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:50:21
  wire [31:0] _FP_mult_4_m_axis_result_tdata;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:50:21
  wire [31:0] _FP_mult_3_m_axis_result_tdata;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:50:21
  wire [31:0] _FP_mult_2_m_axis_result_tdata;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:50:21
  wire [31:0] _FP_mult_1_m_axis_result_tdata;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:50:21
  wire [31:0] _FP_mult_m_axis_result_tdata;	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:50:21
  FP_mult FP_mult (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:50:21
    .aclk                 (clock),
    .s_axis_a_tvalid      (1'h1),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:54:24
    .s_axis_b_tvalid      (1'h1),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:54:24
    .s_axis_a_tdata       (io_in_a_0),
    .s_axis_b_tdata       (io_in_b_0),
    .m_axis_result_tvalid (/* unused */),
    .m_axis_result_tdata  (_FP_mult_m_axis_result_tdata)
  );
  FP_mult FP_mult_1 (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:50:21
    .aclk                 (clock),
    .s_axis_a_tvalid      (1'h1),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:54:24
    .s_axis_b_tvalid      (1'h1),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:54:24
    .s_axis_a_tdata       (io_in_a_1),
    .s_axis_b_tdata       (io_in_b_1),
    .m_axis_result_tvalid (/* unused */),
    .m_axis_result_tdata  (_FP_mult_1_m_axis_result_tdata)
  );
  FP_mult FP_mult_2 (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:50:21
    .aclk                 (clock),
    .s_axis_a_tvalid      (1'h1),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:54:24
    .s_axis_b_tvalid      (1'h1),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:54:24
    .s_axis_a_tdata       (io_in_a_2),
    .s_axis_b_tdata       (io_in_b_2),
    .m_axis_result_tvalid (/* unused */),
    .m_axis_result_tdata  (_FP_mult_2_m_axis_result_tdata)
  );
  FP_mult FP_mult_3 (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:50:21
    .aclk                 (clock),
    .s_axis_a_tvalid      (1'h1),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:54:24
    .s_axis_b_tvalid      (1'h1),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:54:24
    .s_axis_a_tdata       (io_in_a_3),
    .s_axis_b_tdata       (io_in_b_3),
    .m_axis_result_tvalid (/* unused */),
    .m_axis_result_tdata  (_FP_mult_3_m_axis_result_tdata)
  );
  FP_mult FP_mult_4 (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:50:21
    .aclk                 (clock),
    .s_axis_a_tvalid      (1'h1),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:54:24
    .s_axis_b_tvalid      (1'h1),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:54:24
    .s_axis_a_tdata       (io_in_a_4),
    .s_axis_b_tdata       (io_in_b_4),
    .m_axis_result_tvalid (/* unused */),
    .m_axis_result_tdata  (_FP_mult_4_m_axis_result_tdata)
  );
  FP_mult FP_mult_5 (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:50:21
    .aclk                 (clock),
    .s_axis_a_tvalid      (1'h1),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:54:24
    .s_axis_b_tvalid      (1'h1),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:54:24
    .s_axis_a_tdata       (io_in_a_5),
    .s_axis_b_tdata       (io_in_b_5),
    .m_axis_result_tvalid (/* unused */),
    .m_axis_result_tdata  (_FP_mult_5_m_axis_result_tdata)
  );
  FP_mult FP_mult_6 (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:50:21
    .aclk                 (clock),
    .s_axis_a_tvalid      (1'h1),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:54:24
    .s_axis_b_tvalid      (1'h1),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:54:24
    .s_axis_a_tdata       (io_in_a_6),
    .s_axis_b_tdata       (io_in_b_6),
    .m_axis_result_tvalid (/* unused */),
    .m_axis_result_tdata  (_FP_mult_6_m_axis_result_tdata)
  );
  FP_mult FP_mult_7 (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:50:21
    .aclk                 (clock),
    .s_axis_a_tvalid      (1'h1),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:54:24
    .s_axis_b_tvalid      (1'h1),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:54:24
    .s_axis_a_tdata       (io_in_a_7),
    .s_axis_b_tdata       (io_in_b_7),
    .m_axis_result_tvalid (/* unused */),
    .m_axis_result_tdata  (_FP_mult_7_m_axis_result_tdata)
  );
  FP_adder FP_adder (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:62:21
    .aclk                 (clock),
    .s_axis_a_tvalid      (1'h1),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:54:24
    .s_axis_b_tvalid      (1'h1),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:54:24
    .s_axis_a_tdata       (_FP_mult_m_axis_result_tdata),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:50:21
    .s_axis_b_tdata       (_FP_mult_1_m_axis_result_tdata),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:50:21
    .m_axis_result_tvalid (/* unused */),
    .m_axis_result_tdata  (_FP_adder_m_axis_result_tdata)
  );
  FP_adder FP_adder_1 (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:62:21
    .aclk                 (clock),
    .s_axis_a_tvalid      (1'h1),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:54:24
    .s_axis_b_tvalid      (1'h1),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:54:24
    .s_axis_a_tdata       (_FP_adder_m_axis_result_tdata),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:62:21
    .s_axis_b_tdata       (_FP_mult_2_m_axis_result_tdata),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:50:21
    .m_axis_result_tvalid (/* unused */),
    .m_axis_result_tdata  (_FP_adder_1_m_axis_result_tdata)
  );
  FP_adder FP_adder_2 (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:62:21
    .aclk                 (clock),
    .s_axis_a_tvalid      (1'h1),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:54:24
    .s_axis_b_tvalid      (1'h1),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:54:24
    .s_axis_a_tdata       (_FP_adder_1_m_axis_result_tdata),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:62:21
    .s_axis_b_tdata       (_FP_mult_3_m_axis_result_tdata),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:50:21
    .m_axis_result_tvalid (/* unused */),
    .m_axis_result_tdata  (_FP_adder_2_m_axis_result_tdata)
  );
  FP_adder FP_adder_3 (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:62:21
    .aclk                 (clock),
    .s_axis_a_tvalid      (1'h1),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:54:24
    .s_axis_b_tvalid      (1'h1),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:54:24
    .s_axis_a_tdata       (_FP_adder_2_m_axis_result_tdata),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:62:21
    .s_axis_b_tdata       (_FP_mult_4_m_axis_result_tdata),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:50:21
    .m_axis_result_tvalid (/* unused */),
    .m_axis_result_tdata  (_FP_adder_3_m_axis_result_tdata)
  );
  FP_adder FP_adder_4 (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:62:21
    .aclk                 (clock),
    .s_axis_a_tvalid      (1'h1),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:54:24
    .s_axis_b_tvalid      (1'h1),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:54:24
    .s_axis_a_tdata       (_FP_adder_3_m_axis_result_tdata),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:62:21
    .s_axis_b_tdata       (_FP_mult_5_m_axis_result_tdata),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:50:21
    .m_axis_result_tvalid (/* unused */),
    .m_axis_result_tdata  (_FP_adder_4_m_axis_result_tdata)
  );
  FP_adder FP_adder_5 (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:62:21
    .aclk                 (clock),
    .s_axis_a_tvalid      (1'h1),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:54:24
    .s_axis_b_tvalid      (1'h1),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:54:24
    .s_axis_a_tdata       (_FP_adder_4_m_axis_result_tdata),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:62:21
    .s_axis_b_tdata       (_FP_mult_6_m_axis_result_tdata),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:50:21
    .m_axis_result_tvalid (/* unused */),
    .m_axis_result_tdata  (_FP_adder_5_m_axis_result_tdata)
  );
  FP_adder FP_adder_6 (	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:62:21
    .aclk                 (clock),
    .s_axis_a_tvalid      (1'h1),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:54:24
    .s_axis_b_tvalid      (1'h1),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:54:24
    .s_axis_a_tdata       (_FP_adder_5_m_axis_result_tdata),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:62:21
    .s_axis_b_tdata       (_FP_mult_7_m_axis_result_tdata),	// C:\\Stencil_accelerator\\src\\main\\scala\\d_p\\qr.scala:50:21
    .m_axis_result_tvalid (/* unused */),
    .m_axis_result_tdata  (io_out_s)
  );
endmodule


