#!/bin/csh -f
################################################################################
# simulation top mcript
# change modelsim in this file dir and run "do this_file.do"
# project dir ---+---> hdl source dir
#                +---> sim mcript dir
#
################################################################################

# check if current dir has modelsim config file
set has_config  [file exists modelsim.do]
# config modelsim 
if {$has_config==1} { do modelsim.do  ; }

echo "+====================================="
echo "| Creat Lib Work soc                  "
echo "+====================================="
vlib work
vmap work work 

echo "+====================================="
echo "| Complile RTL Code of soc            "
echo "+====================================="
 #+define+ST_WIDTH_3\
     
vlog     -f ../filelist/filelist_st3_datapath.f  
     #+define+ST16_RANDOM_TEST_16X8\
     #+define+ST16_RANDOM_TEST_24X8\
     #+define+ST16_RANDOM_TEST_32X8\

echo "+====================================="
echo "| Compiler Pass                       "
echo "| Being to Run Simulation             "
echo "+====================================="
vsim -voptargs=+acc=npr work.datapath_st3_tb -t 1ns

###################################### mus  ####################################
add wave -noupdate -format logic -hexadecimal datapath_st3_tb/u_datapath_2d/*

add wave -noupdate -format logic -hexadecimal datapath_st3_tb/u_datapath_2d/fifo1/*
add wave -noupdate -format logic -hexadecimal datapath_st3_tb/u_datapath_2d/fifo2/*
add wave -noupdate -format logic -hexadecimal datapath_st3_tb/u_datapath_2d/fifo3/*
add wave -noupdate -format logic -hexadecimal datapath_st3_tb/u_datapath_2d/fifo4/*
add wave -noupdate -format logic -hexadecimal datapath_st3_tb/u_datapath_2d/fifo5/*

#add wave -noupdate -format logic -hexadecimal datapath_st3_tb/u_datapath_2d/SRAM/* 
#add wave -noupdate -format logic -hexadecimal datapath_st3_tb/u_datapath_2d/SRAM/memory_ext/*
#add wave -noupdate -format logic -hexadecimal datapath_st3_tb/u_datapath_2d/fsm/* 
#add wave -noupdate -format logic -hexadecimal datapath_st3_tb/u_datapath_2d/stencil_core_2d/*
#add wave -noupdate -format logic -hexadecimal datapath_st3_tb/u_datapath_2d/stencil_core_2d_1/*
#add wave -noupdate -format logic -hexadecimal datapath_st3_tb/u_datapath_2d/stencil_core_2d_2/*

#add wave -noupdate -format logic -hexadecimal datapath_st3_tb/u_Dot_real/io_in_ready  
#add wave -noupdate -format logic -hexadecimal datapath_st3_tb/u_Dot_real/io_in_weight
#add wave -noupdate -format logic -hexadecimal datapath_st3_tb/u_Dot_real/io_in_data 
#add wave -noupdate -format logic -hexadecimal datapath_st3_tb/u_Dot_real/io_out_data 
#add wave -noupdate -format logic -hexadecimal datapath_st3_tb/u_Dot_real/FP_mult_32_10_v2/* 
#add wave -noupdate -format logic -hexadecimal datapath_st3_tb/u_Dot_real/FP_mult_32_10_v2_1/* 
#add wave -noupdate -format logic -hexadecimal datapath_st3_tb/u_Dot_real/FP_mult_32_10_v2_2/* 
#add wave -noupdate -format logic -hexadecimal datapath_st3_tb/u_Dot_real/FP_add_32_13/* 
#add wave -noupdate -format logic -hexadecimal datapath_st3_tb/u_Dot_real/FP_add_32_13_1/* 




#add wave -noupdate -format logic -hexadecimal tsqr_mc_st4_tb/u_tsqr_mc/*

run 10 us                                                                            

