#!/bin/csh -f
################################################################################
# simulation top mcript
# change modelsim in this file dir and run "do this_file.do"
# project dir ---+---> hdl source dir
#                +---> sim mcript dir
#
################################################################################

# check if current dir has modelsim config file
set has_config  [file exists modelsim.do]
# config modelsim 
if {$has_config==1} { do modelsim.do  ; }

echo "+====================================="
echo "| Creat Lib Work soc                  "
echo "+====================================="
vlib work
vmap work work 

echo "+====================================="
echo "| Complile RTL Code of soc            "
echo "+====================================="
 #+define+ST_WIDTH_3\
     
vlog     -f ../filelist/filelist_stencil_core_2d.f  
     #+define+ST16_RANDOM_TEST_16X8\
     #+define+ST16_RANDOM_TEST_24X8\
     #+define+ST16_RANDOM_TEST_32X8\

echo "+====================================="
echo "| Compiler Pass                       "
echo "| Being to Run Simulation             "
echo "+====================================="
vsim -voptargs=+acc=npr work.stencil_core_2d_tb -t 1ns

###################################### mus  ####################################
add wave -noupdate -format logic -hexadecimal stencil_core_2d_tb/clock  
add wave -noupdate -format logic -hexadecimal stencil_core_2d_tb/u_stencil_core_2d/io_in_ready  
add wave -noupdate -format logic -hexadecimal stencil_core_2d_tb/u_stencil_core_2d/io_in_weight
add wave -noupdate -format logic -hexadecimal stencil_core_2d_tb/u_stencil_core_2d/io_in_matrix 
add wave -noupdate -format logic -hexadecimal stencil_core_2d_tb/u_stencil_core_2d/io_out_data 
add wave -noupdate -format logic -hexadecimal stencil_core_2d_tb/u_stencil_core_2d/Dot_real/*
add wave -noupdate -format logic -hexadecimal stencil_core_2d_tb/u_stencil_core_2d/Dot_real/FP_add_32_13/io_in_a
add wave -noupdate -format logic -hexadecimal stencil_core_2d_tb/u_stencil_core_2d/Dot_real/FP_add_32_13/io_in_b
add wave -noupdate -format logic -hexadecimal stencil_core_2d_tb/u_stencil_core_2d/Dot_real/FP_add_32_13/io_out_s
add wave -noupdate -format logic -hexadecimal stencil_core_2d_tb/u_stencil_core_2d/Dot_real/FP_add_32_13_1/io_in_a
add wave -noupdate -format logic -hexadecimal stencil_core_2d_tb/u_stencil_core_2d/Dot_real/FP_add_32_13_1/io_in_b
add wave -noupdate -format logic -hexadecimal stencil_core_2d_tb/u_stencil_core_2d/Dot_real/FP_add_32_13_1/io_out_s
add wave -noupdate -format logic -hexadecimal stencil_core_2d_tb/u_stencil_core_2d/Dot_real/FP_add_32_13_2/io_in_a
add wave -noupdate -format logic -hexadecimal stencil_core_2d_tb/u_stencil_core_2d/Dot_real/FP_add_32_13_2/io_in_b
add wave -noupdate -format logic -hexadecimal stencil_core_2d_tb/u_stencil_core_2d/Dot_real/FP_add_32_13_2/io_out_s
add wave -noupdate -format logic -hexadecimal stencil_core_2d_tb/u_stencil_core_2d/Dot_real/FP_add_32_13_3/io_in_a
add wave -noupdate -format logic -hexadecimal stencil_core_2d_tb/u_stencil_core_2d/Dot_real/FP_add_32_13_3/io_in_b
add wave -noupdate -format logic -hexadecimal stencil_core_2d_tb/u_stencil_core_2d/Dot_real/FP_add_32_13_3/io_out_s




#add wave -noupdate -format logic -hexadecimal stencil_core_2d_tb/u_stencil_core_2d/FP_mult_32_10_v2/*
add wave -noupdate -format logic -hexadecimal stencil_core_2d_tb/u_stencil_core_2d/*
#add wave -noupdate -format logic -hexadecimal stencil_core_2d_tb/u_stencil_core_2d/acc_reg_0
add wave -noupdate -format logic -hexadecimal stencil_core_2d_tb/u_stencil_core_2d/FP_add_32_13/io_in_a
add wave -noupdate -format logic -hexadecimal stencil_core_2d_tb/u_stencil_core_2d/FP_add_32_13/io_in_b
add wave -noupdate -format logic -hexadecimal stencil_core_2d_tb/u_stencil_core_2d/FP_add_32_13/io_out_s
add wave -noupdate -format logic -hexadecimal stencil_core_2d_tb/u_stencil_core_2d/FP_add_32_13_1/io_in_a
add wave -noupdate -format logic -hexadecimal stencil_core_2d_tb/u_stencil_core_2d/FP_add_32_13_1/io_in_b
add wave -noupdate -format logic -hexadecimal stencil_core_2d_tb/u_stencil_core_2d/FP_add_32_13_1/io_out_s
#
add wave -noupdate -format logic -hexadecimal stencil_core_2d_tb/u_stencil_core_2d/FP_add_32_13_2/io_in_a
add wave -noupdate -format logic -hexadecimal stencil_core_2d_tb/u_stencil_core_2d/FP_add_32_13_2/io_in_b
add wave -noupdate -format logic -hexadecimal stencil_core_2d_tb/u_stencil_core_2d/FP_add_32_13_2/io_out_s
add wave -noupdate -format logic -hexadecimal stencil_core_2d_tb/u_stencil_core_2d/FP_add_32_13_3/io_in_a
add wave -noupdate -format logic -hexadecimal stencil_core_2d_tb/u_stencil_core_2d/FP_add_32_13_3/io_in_b
add wave -noupdate -format logic -hexadecimal stencil_core_2d_tb/u_stencil_core_2d/FP_add_32_13_3/io_out_s


add wave -noupdate -format logic -hexadecimal stencil_core_2d_tb/u_stencil_core_2d/sc_count




#add wave -noupdate -format logic -hexadecimal tsqr_mc_st4_tb/u_tsqr_mc/*

run 10 us                                                                            

